/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Adherent;
import models.tables.records.AdherentRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdherentDao extends DAOImpl<AdherentRecord, models.tables.pojos.Adherent, Long> {

    /**
     * Create a new AdherentDao without any configuration
     */
    public AdherentDao() {
        super(Adherent.ADHERENT, models.tables.pojos.Adherent.class);
    }

    /**
     * Create a new AdherentDao with an attached configuration
     */
    public AdherentDao(Configuration configuration) {
        super(Adherent.ADHERENT, models.tables.pojos.Adherent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Adherent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchById(Long... values) {
        return fetch(Adherent.ADHERENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Adherent fetchOneById(Long value) {
        return fetchOne(Adherent.ADHERENT.ID, value);
    }

    /**
     * Fetch records that have <code>nom_ad IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByNomAd(String... values) {
        return fetch(Adherent.ADHERENT.NOM_AD, values);
    }

    /**
     * Fetch records that have <code>prenom_ad IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByPrenomAd(String... values) {
        return fetch(Adherent.ADHERENT.PRENOM_AD, values);
    }

    /**
     * Fetch records that have <code>fonction IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByFonction(String... values) {
        return fetch(Adherent.ADHERENT.FONCTION, values);
    }

    /**
     * Fetch records that have <code>date_naiss IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByDateNaiss(Timestamp... values) {
        return fetch(Adherent.ADHERENT.DATE_NAISS, values);
    }

    /**
     * Fetch records that have <code>date_prise_service IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByDatePriseService(Timestamp... values) {
        return fetch(Adherent.ADHERENT.DATE_PRISE_SERVICE, values);
    }

    /**
     * Fetch records that have <code>picture IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByPicture(String... values) {
        return fetch(Adherent.ADHERENT.PICTURE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByWhenDone(Timestamp... values) {
        return fetch(Adherent.ADHERENT.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByWhoDone(String... values) {
        return fetch(Adherent.ADHERENT.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByOnDeleted(Boolean... values) {
        return fetch(Adherent.ADHERENT.ON_DELETED, values);
    }

    /**
     * Fetch records that have <code>direction IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByDirection(Long... values) {
        return fetch(Adherent.ADHERENT.DIRECTION, values);
    }

    /**
     * Fetch records that have <code>division IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByDivision(Long... values) {
        return fetch(Adherent.ADHERENT.DIVISION, values);
    }

    /**
     * Fetch records that have <code>service IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByService(Long... values) {
        return fetch(Adherent.ADHERENT.SERVICE, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByTelephone(String... values) {
        return fetch(Adherent.ADHERENT.TELEPHONE, values);
    }

    /**
     * Fetch records that have <code>matricule IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByMatricule(String... values) {
        return fetch(Adherent.ADHERENT.MATRICULE, values);
    }

    /**
     * Fetch records that have <code>structure IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByStructure(String... values) {
        return fetch(Adherent.ADHERENT.STRUCTURE, values);
    }

    /**
     * Fetch records that have <code>structure_sigle IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByStructureSigle(String... values) {
        return fetch(Adherent.ADHERENT.STRUCTURE_SIGLE, values);
    }

    /**
     * Fetch records that have <code>code_programme IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByCodeProgramme(String... values) {
        return fetch(Adherent.ADHERENT.CODE_PROGRAMME, values);
    }

    /**
     * Fetch records that have <code>categorie IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByCategorie(String... values) {
        return fetch(Adherent.ADHERENT.CATEGORIE, values);
    }

    /**
     * Fetch records that have <code>sexe IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchBySexe(String... values) {
        return fetch(Adherent.ADHERENT.SEXE, values);
    }

    /**
     * Fetch records that have <code>mat IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByMat(Long... values) {
        return fetch(Adherent.ADHERENT.MAT, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByEmail(String... values) {
        return fetch(Adherent.ADHERENT.EMAIL, values);
    }

    /**
     * Fetch records that have <code>is_member IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByIsMember(Boolean... values) {
        return fetch(Adherent.ADHERENT.IS_MEMBER, values);
    }

    /**
     * Fetch records that have <code>is_ok_for_printing IN (values)</code>
     */
    public List<models.tables.pojos.Adherent> fetchByIsOkForPrinting(Boolean... values) {
        return fetch(Adherent.ADHERENT.IS_OK_FOR_PRINTING, values);
    }
}
