/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Budget;
import models.tables.records.BudgetRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BudgetDao extends DAOImpl<BudgetRecord, models.tables.pojos.Budget, Long> {

    /**
     * Create a new BudgetDao without any configuration
     */
    public BudgetDao() {
        super(Budget.BUDGET, models.tables.pojos.Budget.class);
    }

    /**
     * Create a new BudgetDao with an attached configuration
     */
    public BudgetDao(Configuration configuration) {
        super(Budget.BUDGET, models.tables.pojos.Budget.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Budget object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchById(Long... values) {
        return fetch(Budget.BUDGET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Budget fetchOneById(Long value) {
        return fetchOne(Budget.BUDGET.ID, value);
    }

    /**
     * Fetch records that have <code>gestion IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByGestion(Long... values) {
        return fetch(Budget.BUDGET.GESTION, values);
    }

    /**
     * Fetch records that have <code>compte IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByCompte(Long... values) {
        return fetch(Budget.BUDGET.COMPTE, values);
    }

    /**
     * Fetch records that have <code>type_buget IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByTypeBuget(String... values) {
        return fetch(Budget.BUDGET.TYPE_BUGET, values);
    }

    /**
     * Fetch records that have <code>montant IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByMontant(Long... values) {
        return fetch(Budget.BUDGET.MONTANT, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByIsDeleted(Boolean... values) {
        return fetch(Budget.BUDGET.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByWhoDone(String... values) {
        return fetch(Budget.BUDGET.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Budget> fetchByWhenDone(Timestamp... values) {
        return fetch(Budget.BUDGET.WHEN_DONE, values);
    }
}
