/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.CategorieCompte;
import models.tables.records.CategorieCompteRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategorieCompteDao extends DAOImpl<CategorieCompteRecord, models.tables.pojos.CategorieCompte, Long> {

    /**
     * Create a new CategorieCompteDao without any configuration
     */
    public CategorieCompteDao() {
        super(CategorieCompte.CATEGORIE_COMPTE, models.tables.pojos.CategorieCompte.class);
    }

    /**
     * Create a new CategorieCompteDao with an attached configuration
     */
    public CategorieCompteDao(Configuration configuration) {
        super(CategorieCompte.CATEGORIE_COMPTE, models.tables.pojos.CategorieCompte.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.CategorieCompte object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchById(Long... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.CategorieCompte fetchOneById(Long value) {
        return fetchOne(CategorieCompte.CATEGORIE_COMPTE.ID, value);
    }

    /**
     * Fetch records that have <code>num_categore IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByNumCategore(Long... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.NUM_CATEGORE, values);
    }

    /**
     * Fetch a unique record that has <code>num_categore = value</code>
     */
    public models.tables.pojos.CategorieCompte fetchOneByNumCategore(Long value) {
        return fetchOne(CategorieCompte.CATEGORIE_COMPTE.NUM_CATEGORE, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByLibelle(String... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByIsDeleted(Boolean... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByWhenDone(Timestamp... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByWhoDone(String... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>is_for_budget IN (values)</code>
     */
    public List<models.tables.pojos.CategorieCompte> fetchByIsForBudget(Boolean... values) {
        return fetch(CategorieCompte.CATEGORIE_COMPTE.IS_FOR_BUDGET, values);
    }
}
