/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.ClassCompte;
import models.tables.records.ClassCompteRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassCompteDao extends DAOImpl<ClassCompteRecord, models.tables.pojos.ClassCompte, Long> {

    /**
     * Create a new ClassCompteDao without any configuration
     */
    public ClassCompteDao() {
        super(ClassCompte.CLASS_COMPTE, models.tables.pojos.ClassCompte.class);
    }

    /**
     * Create a new ClassCompteDao with an attached configuration
     */
    public ClassCompteDao(Configuration configuration) {
        super(ClassCompte.CLASS_COMPTE, models.tables.pojos.ClassCompte.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.ClassCompte object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchById(Long... values) {
        return fetch(ClassCompte.CLASS_COMPTE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.ClassCompte fetchOneById(Long value) {
        return fetchOne(ClassCompte.CLASS_COMPTE.ID, value);
    }

    /**
     * Fetch records that have <code>categorie IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByCategorie(Long... values) {
        return fetch(ClassCompte.CLASS_COMPTE.CATEGORIE, values);
    }

    /**
     * Fetch records that have <code>libelle_compte IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByLibelleCompte(String... values) {
        return fetch(ClassCompte.CLASS_COMPTE.LIBELLE_COMPTE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByDescription(String... values) {
        return fetch(ClassCompte.CLASS_COMPTE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByIsDeleted(Boolean... values) {
        return fetch(ClassCompte.CLASS_COMPTE.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByWhoDone(String... values) {
        return fetch(ClassCompte.CLASS_COMPTE.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByWhenDone(Timestamp... values) {
        return fetch(ClassCompte.CLASS_COMPTE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>is_for_budget IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByIsForBudget(Boolean... values) {
        return fetch(ClassCompte.CLASS_COMPTE.IS_FOR_BUDGET, values);
    }

    /**
     * Fetch records that have <code>num_compte IN (values)</code>
     */
    public List<models.tables.pojos.ClassCompte> fetchByNumCompte(Long... values) {
        return fetch(ClassCompte.CLASS_COMPTE.NUM_COMPTE, values);
    }

    /**
     * Fetch a unique record that has <code>num_compte = value</code>
     */
    public models.tables.pojos.ClassCompte fetchOneByNumCompte(Long value) {
        return fetchOne(ClassCompte.CLASS_COMPTE.NUM_COMPTE, value);
    }
}
