/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Connexion;
import models.tables.records.ConnexionRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnexionDao extends DAOImpl<ConnexionRecord, models.tables.pojos.Connexion, Long> {

    /**
     * Create a new ConnexionDao without any configuration
     */
    public ConnexionDao() {
        super(Connexion.CONNEXION, models.tables.pojos.Connexion.class);
    }

    /**
     * Create a new ConnexionDao with an attached configuration
     */
    public ConnexionDao(Configuration configuration) {
        super(Connexion.CONNEXION, models.tables.pojos.Connexion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Connexion object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Connexion> fetchById(Long... values) {
        return fetch(Connexion.CONNEXION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Connexion fetchOneById(Long value) {
        return fetchOne(Connexion.CONNEXION.ID, value);
    }

    /**
     * Fetch records that have <code>user IN (values)</code>
     */
    public List<models.tables.pojos.Connexion> fetchByUser(String... values) {
        return fetch(Connexion.CONNEXION.USER, values);
    }

    /**
     * Fetch records that have <code>profil IN (values)</code>
     */
    public List<models.tables.pojos.Connexion> fetchByProfil(String... values) {
        return fetch(Connexion.CONNEXION.PROFIL, values);
    }

    /**
     * Fetch records that have <code>when_down IN (values)</code>
     */
    public List<models.tables.pojos.Connexion> fetchByWhenDown(Timestamp... values) {
        return fetch(Connexion.CONNEXION.WHEN_DOWN, values);
    }
}
