/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Depense;
import models.tables.records.DepenseRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepenseDao extends DAOImpl<DepenseRecord, models.tables.pojos.Depense, Long> {

    /**
     * Create a new DepenseDao without any configuration
     */
    public DepenseDao() {
        super(Depense.DEPENSE, models.tables.pojos.Depense.class);
    }

    /**
     * Create a new DepenseDao with an attached configuration
     */
    public DepenseDao(Configuration configuration) {
        super(Depense.DEPENSE, models.tables.pojos.Depense.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Depense object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchById(Long... values) {
        return fetch(Depense.DEPENSE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Depense fetchOneById(Long value) {
        return fetchOne(Depense.DEPENSE.ID, value);
    }

    /**
     * Fetch records that have <code>ref_depense IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByRefDepense(String... values) {
        return fetch(Depense.DEPENSE.REF_DEPENSE, values);
    }

    /**
     * Fetch records that have <code>date_depense IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByDateDepense(Timestamp... values) {
        return fetch(Depense.DEPENSE.DATE_DEPENSE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByIsDeleted(Boolean... values) {
        return fetch(Depense.DEPENSE.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByWhoDone(String... values) {
        return fetch(Depense.DEPENSE.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByWhenDone(Timestamp... values) {
        return fetch(Depense.DEPENSE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<models.tables.pojos.Depense> fetchByLastUpdate(Timestamp... values) {
        return fetch(Depense.DEPENSE.LAST_UPDATE, values);
    }
}
