/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Direction;
import models.tables.records.DirectionRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectionDao extends DAOImpl<DirectionRecord, models.tables.pojos.Direction, Long> {

    /**
     * Create a new DirectionDao without any configuration
     */
    public DirectionDao() {
        super(Direction.DIRECTION, models.tables.pojos.Direction.class);
    }

    /**
     * Create a new DirectionDao with an attached configuration
     */
    public DirectionDao(Configuration configuration) {
        super(Direction.DIRECTION, models.tables.pojos.Direction.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Direction object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchById(Long... values) {
        return fetch(Direction.DIRECTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Direction fetchOneById(Long value) {
        return fetchOne(Direction.DIRECTION.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchByCode(String... values) {
        return fetch(Direction.DIRECTION.CODE, values);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchByLibelle(String... values) {
        return fetch(Direction.DIRECTION.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchByWhenDone(Timestamp... values) {
        return fetch(Direction.DIRECTION.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchByWhoDone(String... values) {
        return fetch(Direction.DIRECTION.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Direction> fetchByOnDeleted(Boolean... values) {
        return fetch(Direction.DIRECTION.ON_DELETED, values);
    }
}
