/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import models.tables.Params;
import models.tables.records.ParamsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParamsDao extends DAOImpl<ParamsRecord, models.tables.pojos.Params, Long> {

    /**
     * Create a new ParamsDao without any configuration
     */
    public ParamsDao() {
        super(Params.PARAMS, models.tables.pojos.Params.class);
    }

    /**
     * Create a new ParamsDao with an attached configuration
     */
    public ParamsDao(Configuration configuration) {
        super(Params.PARAMS, models.tables.pojos.Params.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Params object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Params> fetchById(Long... values) {
        return fetch(Params.PARAMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Params fetchOneById(Long value) {
        return fetchOne(Params.PARAMS.ID, value);
    }

    /**
     * Fetch records that have <code>gestion IN (values)</code>
     */
    public List<models.tables.pojos.Params> fetchByGestion(String... values) {
        return fetch(Params.PARAMS.GESTION, values);
    }

    /**
     * Fetch records that have <code>plafond IN (values)</code>
     */
    public List<models.tables.pojos.Params> fetchByPlafond(Long... values) {
        return fetch(Params.PARAMS.PLAFOND, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Params> fetchByIsDeleted(Boolean... values) {
        return fetch(Params.PARAMS.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>seuil_alerte IN (values)</code>
     */
    public List<models.tables.pojos.Params> fetchBySeuilAlerte(Long... values) {
        return fetch(Params.PARAMS.SEUIL_ALERTE, values);
    }
}
