/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Region;
import models.tables.records.RegionRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionDao extends DAOImpl<RegionRecord, models.tables.pojos.Region, Long> {

    /**
     * Create a new RegionDao without any configuration
     */
    public RegionDao() {
        super(Region.REGION, models.tables.pojos.Region.class);
    }

    /**
     * Create a new RegionDao with an attached configuration
     */
    public RegionDao(Configuration configuration) {
        super(Region.REGION, models.tables.pojos.Region.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Region object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Region> fetchById(Long... values) {
        return fetch(Region.REGION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Region fetchOneById(Long value) {
        return fetchOne(Region.REGION.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.tables.pojos.Region> fetchByLibelle(String... values) {
        return fetch(Region.REGION.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Region> fetchByWhoDone(String... values) {
        return fetch(Region.REGION.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Region> fetchByWhenDone(Timestamp... values) {
        return fetch(Region.REGION.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Region> fetchByIsDeleted(Boolean... values) {
        return fetch(Region.REGION.IS_DELETED, values);
    }
}
