/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.ReglementDetail;
import models.tables.records.ReglementDetailRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReglementDetailDao extends DAOImpl<ReglementDetailRecord, models.tables.pojos.ReglementDetail, Long> {

    /**
     * Create a new ReglementDetailDao without any configuration
     */
    public ReglementDetailDao() {
        super(ReglementDetail.REGLEMENT_DETAIL, models.tables.pojos.ReglementDetail.class);
    }

    /**
     * Create a new ReglementDetailDao with an attached configuration
     */
    public ReglementDetailDao(Configuration configuration) {
        super(ReglementDetail.REGLEMENT_DETAIL, models.tables.pojos.ReglementDetail.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.ReglementDetail object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchById(Long... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.ReglementDetail fetchOneById(Long value) {
        return fetchOne(ReglementDetail.REGLEMENT_DETAIL.ID, value);
    }

    /**
     * Fetch records that have <code>reglement IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByReglement(Long... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.REGLEMENT, values);
    }

    /**
     * Fetch records that have <code>intitule IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByIntitule(String... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.INTITULE, values);
    }

    /**
     * Fetch records that have <code>montant IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByMontant(Long... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.MONTANT, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByWhoDone(String... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByWhenDone(Timestamp... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByOnDeleted(Boolean... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.ON_DELETED, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<models.tables.pojos.ReglementDetail> fetchByLastUpdate(Timestamp... values) {
        return fetch(ReglementDetail.REGLEMENT_DETAIL.LAST_UPDATE, values);
    }
}
