/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Reglement;
import models.tables.records.ReglementRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReglementDao extends DAOImpl<ReglementRecord, models.tables.pojos.Reglement, Long> {

    /**
     * Create a new ReglementDao without any configuration
     */
    public ReglementDao() {
        super(Reglement.REGLEMENT, models.tables.pojos.Reglement.class);
    }

    /**
     * Create a new ReglementDao with an attached configuration
     */
    public ReglementDao(Configuration configuration) {
        super(Reglement.REGLEMENT, models.tables.pojos.Reglement.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Reglement object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchById(Long... values) {
        return fetch(Reglement.REGLEMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Reglement fetchOneById(Long value) {
        return fetchOne(Reglement.REGLEMENT.ID, value);
    }

    /**
     * Fetch records that have <code>adherent IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByAdherent(Long... values) {
        return fetch(Reglement.REGLEMENT.ADHERENT, values);
    }

    /**
     * Fetch records that have <code>ref_facture IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByRefFacture(String... values) {
        return fetch(Reglement.REGLEMENT.REF_FACTURE, values);
    }

    /**
     * Fetch records that have <code>structure IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByStructure(Long... values) {
        return fetch(Reglement.REGLEMENT.STRUCTURE, values);
    }

    /**
     * Fetch records that have <code>date_payement IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByDatePayement(Timestamp... values) {
        return fetch(Reglement.REGLEMENT.DATE_PAYEMENT, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByWhoDone(String... values) {
        return fetch(Reglement.REGLEMENT.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByWhenDone(Timestamp... values) {
        return fetch(Reglement.REGLEMENT.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByOnDeleted(Boolean... values) {
        return fetch(Reglement.REGLEMENT.ON_DELETED, values);
    }

    /**
     * Fetch records that have <code>type_prestation IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByTypePrestation(Long... values) {
        return fetch(Reglement.REGLEMENT.TYPE_PRESTATION, values);
    }

    /**
     * Fetch records that have <code>ayant_droit IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByAyantDroit(Long... values) {
        return fetch(Reglement.REGLEMENT.AYANT_DROIT, values);
    }

    /**
     * Fetch records that have <code>structure_emettrice_rembourssement IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByStructureEmettriceRembourssement(String... values) {
        return fetch(Reglement.REGLEMENT.STRUCTURE_EMETTRICE_REMBOURSSEMENT, values);
    }

    /**
     * Fetch records that have <code>tel_structure_emettrice IN (values)</code>
     */
    public List<models.tables.pojos.Reglement> fetchByTelStructureEmettrice(String... values) {
        return fetch(Reglement.REGLEMENT.TEL_STRUCTURE_EMETTRICE, values);
    }
}
