/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Service;
import models.tables.records.ServiceRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceDao extends DAOImpl<ServiceRecord, models.tables.pojos.Service, Long> {

    /**
     * Create a new ServiceDao without any configuration
     */
    public ServiceDao() {
        super(Service.SERVICE, models.tables.pojos.Service.class);
    }

    /**
     * Create a new ServiceDao with an attached configuration
     */
    public ServiceDao(Configuration configuration) {
        super(Service.SERVICE, models.tables.pojos.Service.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.Service object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchById(Long... values) {
        return fetch(Service.SERVICE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Service fetchOneById(Long value) {
        return fetchOne(Service.SERVICE.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByCode(String... values) {
        return fetch(Service.SERVICE.CODE, values);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByLibelle(String... values) {
        return fetch(Service.SERVICE.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByWhenDone(Timestamp... values) {
        return fetch(Service.SERVICE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByWhoDone(String... values) {
        return fetch(Service.SERVICE.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByOnDeleted(Boolean... values) {
        return fetch(Service.SERVICE.ON_DELETED, values);
    }

    /**
     * Fetch records that have <code>division IN (values)</code>
     */
    public List<models.tables.pojos.Service> fetchByDivision(Long... values) {
        return fetch(Service.SERVICE.DIVISION, values);
    }
}
