/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import models.tables.TypePrestation;
import models.tables.records.TypePrestationRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePrestationDao extends DAOImpl<TypePrestationRecord, models.tables.pojos.TypePrestation, Long> {

    /**
     * Create a new TypePrestationDao without any configuration
     */
    public TypePrestationDao() {
        super(TypePrestation.TYPE_PRESTATION, models.tables.pojos.TypePrestation.class);
    }

    /**
     * Create a new TypePrestationDao with an attached configuration
     */
    public TypePrestationDao(Configuration configuration) {
        super(TypePrestation.TYPE_PRESTATION, models.tables.pojos.TypePrestation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.TypePrestation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.TypePrestation> fetchById(Long... values) {
        return fetch(TypePrestation.TYPE_PRESTATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.TypePrestation fetchOneById(Long value) {
        return fetchOne(TypePrestation.TYPE_PRESTATION.ID, value);
    }

    /**
     * Fetch records that have <code>prestation IN (values)</code>
     */
    public List<models.tables.pojos.TypePrestation> fetchByPrestation(String... values) {
        return fetch(TypePrestation.TYPE_PRESTATION.PRESTATION, values);
    }

    /**
     * Fetch records that have <code>couverture IN (values)</code>
     */
    public List<models.tables.pojos.TypePrestation> fetchByCouverture(String... values) {
        return fetch(TypePrestation.TYPE_PRESTATION.COUVERTURE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.tables.pojos.TypePrestation> fetchByOnDeleted(Boolean... values) {
        return fetch(TypePrestation.TYPE_PRESTATION.ON_DELETED, values);
    }
}
