/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Adherent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdherentRecord extends UpdatableRecordImpl<AdherentRecord> {

    private static final long serialVersionUID = 152910626;

    /**
     * Setter for <code>public.adherent.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.adherent.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.adherent.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.adherent.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.adherent.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.adherent.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.adherent.fonction</code>.
     */
    public void setFonction(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.adherent.fonction</code>.
     */
    public String getFonction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.adherent.date_naiss</code>.
     */
    public void setDateNaiss(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.adherent.date_naiss</code>.
     */
    public Timestamp getDateNaiss() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.adherent.date_prise_service</code>.
     */
    public void setDatePriseService(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.adherent.date_prise_service</code>.
     */
    public Timestamp getDatePriseService() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.adherent.picture</code>.
     */
    public void setPicture(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.adherent.picture</code>.
     */
    public String getPicture() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.adherent.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.adherent.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.adherent.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.adherent.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.adherent.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.adherent.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.adherent.direction</code>.
     */
    public void setDirection(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.adherent.direction</code>.
     */
    public Long getDirection() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.adherent.division</code>.
     */
    public void setDivision(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.adherent.division</code>.
     */
    public Long getDivision() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.adherent.service</code>.
     */
    public void setService(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.adherent.service</code>.
     */
    public Long getService() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.adherent.telephone</code>.
     */
    public void setTelephone(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.adherent.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.adherent.matricule</code>.
     */
    public void setMatricule(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.adherent.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.adherent.structure</code>.
     */
    public void setStructure(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.adherent.structure</code>.
     */
    public String getStructure() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.adherent.structure_sigle</code>.
     */
    public void setStructureSigle(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.adherent.structure_sigle</code>.
     */
    public String getStructureSigle() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.adherent.code_programme</code>.
     */
    public void setCodeProgramme(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.adherent.code_programme</code>.
     */
    public String getCodeProgramme() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.adherent.categorie</code>.
     */
    public void setCategorie(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.adherent.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.adherent.sexe</code>.
     */
    public void setSexe(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.adherent.sexe</code>.
     */
    public String getSexe() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.adherent.mat</code>.
     */
    public void setMat(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.adherent.mat</code>.
     */
    public Long getMat() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.adherent.email</code>.
     */
    public void setEmail(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.adherent.email</code>.
     */
    public String getEmail() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.adherent.is_member</code>.
     */
    public void setIsMember(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.adherent.is_member</code>.
     */
    public Boolean getIsMember() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>public.adherent.is_ok_for_printing</code>.
     */
    public void setIsOkForPrinting(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.adherent.is_ok_for_printing</code>.
     */
    public Boolean getIsOkForPrinting() {
        return (Boolean) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdherentRecord
     */
    public AdherentRecord() {
        super(Adherent.ADHERENT);
    }

    /**
     * Create a detached, initialised AdherentRecord
     */
    public AdherentRecord(Long id, String nomAd, String prenomAd, String fonction, Timestamp dateNaiss, Timestamp datePriseService, String picture, Timestamp whenDone, String whoDone, Boolean onDeleted, Long direction, Long division, Long service, String telephone, String matricule, String structure, String structureSigle, String codeProgramme, String categorie, String sexe, Long mat, String email, Boolean isMember, Boolean isOkForPrinting) {
        super(Adherent.ADHERENT);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, fonction);
        set(4, dateNaiss);
        set(5, datePriseService);
        set(6, picture);
        set(7, whenDone);
        set(8, whoDone);
        set(9, onDeleted);
        set(10, direction);
        set(11, division);
        set(12, service);
        set(13, telephone);
        set(14, matricule);
        set(15, structure);
        set(16, structureSigle);
        set(17, codeProgramme);
        set(18, categorie);
        set(19, sexe);
        set(20, mat);
        set(21, email);
        set(22, isMember);
        set(23, isOkForPrinting);
    }
}
