/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.AdherentTmp;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdherentTmpRecord extends TableRecordImpl<AdherentTmpRecord> implements Record13<Long, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1410561364;

    /**
     * Setter for <code>public.adherent_tmp.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.adherent_tmp.matricule</code>.
     */
    public void setMatricule(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.adherent_tmp.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.adherent_tmp.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.adherent_tmp.categorie</code>.
     */
    public void setCategorie(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.adherent_tmp.fonction</code>.
     */
    public void setFonction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.fonction</code>.
     */
    public String getFonction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.adherent_tmp.structur</code>.
     */
    public void setStructur(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.structur</code>.
     */
    public String getStructur() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.adherent_tmp.programe</code>.
     */
    public void setPrograme(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.programe</code>.
     */
    public String getPrograme() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.adherent_tmp.sexe</code>.
     */
    public void setSexe(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.sexe</code>.
     */
    public String getSexe() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.adherent_tmp.date_naiss</code>.
     */
    public void setDateNaiss(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.date_naiss</code>.
     */
    public String getDateNaiss() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.adherent_tmp.date_prise_service</code>.
     */
    public void setDatePriseService(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.date_prise_service</code>.
     */
    public String getDatePriseService() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.adherent_tmp.telephone</code>.
     */
    public void setTelephone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.adherent_tmp.structure_sigle</code>.
     */
    public void setStructureSigle(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.adherent_tmp.structure_sigle</code>.
     */
    public String getStructureSigle() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AdherentTmp.ADHERENT_TMP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AdherentTmp.ADHERENT_TMP.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AdherentTmp.ADHERENT_TMP.NOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AdherentTmp.ADHERENT_TMP.PRENOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AdherentTmp.ADHERENT_TMP.CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AdherentTmp.ADHERENT_TMP.FONCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AdherentTmp.ADHERENT_TMP.STRUCTUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return AdherentTmp.ADHERENT_TMP.PROGRAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AdherentTmp.ADHERENT_TMP.SEXE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AdherentTmp.ADHERENT_TMP.DATE_NAISS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return AdherentTmp.ADHERENT_TMP.DATE_PRISE_SERVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return AdherentTmp.ADHERENT_TMP.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return AdherentTmp.ADHERENT_TMP.STRUCTURE_SIGLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFonction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStructur();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPrograme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDatePriseService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getStructureSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFonction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStructur();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPrograme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDatePriseService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getStructureSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value2(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value3(String value) {
        setNomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value4(String value) {
        setPrenomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value5(String value) {
        setCategorie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value6(String value) {
        setFonction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value7(String value) {
        setStructur(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value8(String value) {
        setPrograme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value9(String value) {
        setSexe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value10(String value) {
        setDateNaiss(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value11(String value) {
        setDatePriseService(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value12(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord value13(String value) {
        setStructureSigle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdherentTmpRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdherentTmpRecord
     */
    public AdherentTmpRecord() {
        super(AdherentTmp.ADHERENT_TMP);
    }

    /**
     * Create a detached, initialised AdherentTmpRecord
     */
    public AdherentTmpRecord(Long id, String matricule, String nomAd, String prenomAd, String categorie, String fonction, String structur, String programe, String sexe, String dateNaiss, String datePriseService, String telephone, String structureSigle) {
        super(AdherentTmp.ADHERENT_TMP);

        set(0, id);
        set(1, matricule);
        set(2, nomAd);
        set(3, prenomAd);
        set(4, categorie);
        set(5, fonction);
        set(6, structur);
        set(7, programe);
        set(8, sexe);
        set(9, dateNaiss);
        set(10, datePriseService);
        set(11, telephone);
        set(12, structureSigle);
    }
}
