/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.CategorieCompte;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategorieCompteRecord extends UpdatableRecordImpl<CategorieCompteRecord> implements Record7<Long, Long, String, Boolean, Timestamp, String, Boolean> {

    private static final long serialVersionUID = 429661533;

    /**
     * Setter for <code>public.categorie_compte.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.categorie_compte.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.categorie_compte.num_categore</code>.
     */
    public void setNumCategore(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.categorie_compte.num_categore</code>.
     */
    public Long getNumCategore() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.categorie_compte.libelle</code>.
     */
    public void setLibelle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.categorie_compte.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.categorie_compte.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.categorie_compte.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.categorie_compte.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.categorie_compte.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.categorie_compte.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.categorie_compte.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.categorie_compte.is_for_budget</code>.
     */
    public void setIsForBudget(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.categorie_compte.is_for_budget</code>.
     */
    public Boolean getIsForBudget() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, Boolean, Timestamp, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, Boolean, Timestamp, String, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CategorieCompte.CATEGORIE_COMPTE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CategorieCompte.CATEGORIE_COMPTE.NUM_CATEGORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CategorieCompte.CATEGORIE_COMPTE.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return CategorieCompte.CATEGORIE_COMPTE.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CategorieCompte.CATEGORIE_COMPTE.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CategorieCompte.CATEGORIE_COMPTE.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return CategorieCompte.CATEGORIE_COMPTE.IS_FOR_BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNumCategore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getIsForBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNumCategore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIsForBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value2(Long value) {
        setNumCategore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value3(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value4(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value5(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value6(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord value7(Boolean value) {
        setIsForBudget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategorieCompteRecord values(Long value1, Long value2, String value3, Boolean value4, Timestamp value5, String value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategorieCompteRecord
     */
    public CategorieCompteRecord() {
        super(CategorieCompte.CATEGORIE_COMPTE);
    }

    /**
     * Create a detached, initialised CategorieCompteRecord
     */
    public CategorieCompteRecord(Long id, Long numCategore, String libelle, Boolean isDeleted, Timestamp whenDone, String whoDone, Boolean isForBudget) {
        super(CategorieCompte.CATEGORIE_COMPTE);

        set(0, id);
        set(1, numCategore);
        set(2, libelle);
        set(3, isDeleted);
        set(4, whenDone);
        set(5, whoDone);
        set(6, isForBudget);
    }
}
