/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.ClassCompte;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassCompteRecord extends UpdatableRecordImpl<ClassCompteRecord> implements Record9<Long, Long, String, String, Boolean, String, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = 51376009;

    /**
     * Setter for <code>public.class_compte.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.class_compte.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.class_compte.categorie</code>.
     */
    public void setCategorie(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.class_compte.categorie</code>.
     */
    public Long getCategorie() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.class_compte.libelle_compte</code>.
     */
    public void setLibelleCompte(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.class_compte.libelle_compte</code>.
     */
    public String getLibelleCompte() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.class_compte.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.class_compte.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.class_compte.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.class_compte.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.class_compte.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.class_compte.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.class_compte.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.class_compte.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.class_compte.is_for_budget</code>.
     */
    public void setIsForBudget(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.class_compte.is_for_budget</code>.
     */
    public Boolean getIsForBudget() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.class_compte.num_compte</code>.
     */
    public void setNumCompte(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.class_compte.num_compte</code>.
     */
    public Long getNumCompte() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, Boolean, String, Timestamp, Boolean, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, Boolean, String, Timestamp, Boolean, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ClassCompte.CLASS_COMPTE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ClassCompte.CLASS_COMPTE.CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ClassCompte.CLASS_COMPTE.LIBELLE_COMPTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ClassCompte.CLASS_COMPTE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return ClassCompte.CLASS_COMPTE.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ClassCompte.CLASS_COMPTE.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ClassCompte.CLASS_COMPTE.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return ClassCompte.CLASS_COMPTE.IS_FOR_BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return ClassCompte.CLASS_COMPTE.NUM_COMPTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLibelleCompte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getIsForBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getNumCompte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLibelleCompte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getIsForBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getNumCompte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value2(Long value) {
        setCategorie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value3(String value) {
        setLibelleCompte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value6(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value7(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value8(Boolean value) {
        setIsForBudget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord value9(Long value) {
        setNumCompte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompteRecord values(Long value1, Long value2, String value3, String value4, Boolean value5, String value6, Timestamp value7, Boolean value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassCompteRecord
     */
    public ClassCompteRecord() {
        super(ClassCompte.CLASS_COMPTE);
    }

    /**
     * Create a detached, initialised ClassCompteRecord
     */
    public ClassCompteRecord(Long id, Long categorie, String libelleCompte, String description, Boolean isDeleted, String whoDone, Timestamp whenDone, Boolean isForBudget, Long numCompte) {
        super(ClassCompte.CLASS_COMPTE);

        set(0, id);
        set(1, categorie);
        set(2, libelleCompte);
        set(3, description);
        set(4, isDeleted);
        set(5, whoDone);
        set(6, whenDone);
        set(7, isForBudget);
        set(8, numCompte);
    }
}
