/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Division;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DivisionRecord extends UpdatableRecordImpl<DivisionRecord> implements Record7<Long, String, String, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = 1316668657;

    /**
     * Setter for <code>public.division.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.division.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.division.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.division.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.division.libelle</code>.
     */
    public void setLibelle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.division.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.division.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.division.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.division.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.division.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.division.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.division.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.division.direction</code>.
     */
    public void setDirection(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.division.direction</code>.
     */
    public Long getDirection() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Division.DIVISION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Division.DIVISION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Division.DIVISION.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Division.DIVISION.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Division.DIVISION.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Division.DIVISION.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Division.DIVISION.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value3(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value4(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value5(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value6(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord value7(Long value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DivisionRecord values(Long value1, String value2, String value3, Timestamp value4, String value5, Boolean value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DivisionRecord
     */
    public DivisionRecord() {
        super(Division.DIVISION);
    }

    /**
     * Create a detached, initialised DivisionRecord
     */
    public DivisionRecord(Long id, String code, String libelle, Timestamp whenDone, String whoDone, Boolean onDeleted, Long direction) {
        super(Division.DIVISION);

        set(0, id);
        set(1, code);
        set(2, libelle);
        set(3, whenDone);
        set(4, whoDone);
        set(5, onDeleted);
        set(6, direction);
    }
}
