/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Email;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecord extends UpdatableRecordImpl<EmailRecord> implements Record6<Long, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 2117227690;

    /**
     * Setter for <code>public.email.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.email.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.email.destinateur</code>.
     */
    public void setDestinateur(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.email.destinateur</code>.
     */
    public String getDestinateur() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.email.subject</code>.
     */
    public void setSubject(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.email.subject</code>.
     */
    public String getSubject() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.email.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.email.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.email.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.email.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.email.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.email.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Email.EMAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Email.EMAIL.DESTINATEUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Email.EMAIL.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Email.EMAIL.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Email.EMAIL.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Email.EMAIL.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDestinateur();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDestinateur();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value2(String value) {
        setDestinateur(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value3(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value5(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value6(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailRecord
     */
    public EmailRecord() {
        super(Email.EMAIL);
    }

    /**
     * Create a detached, initialised EmailRecord
     */
    public EmailRecord(Long id, String destinateur, String subject, String message, String whoDone, Timestamp whenDone) {
        super(Email.EMAIL);

        set(0, id);
        set(1, destinateur);
        set(2, subject);
        set(3, message);
        set(4, whoDone);
        set(5, whenDone);
    }
}
