/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.Params;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParamsRecord extends UpdatableRecordImpl<ParamsRecord> implements Record5<Long, String, Long, Boolean, Long> {

    private static final long serialVersionUID = -1925330183;

    /**
     * Setter for <code>public.params.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.params.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.params.gestion</code>.
     */
    public void setGestion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.params.gestion</code>.
     */
    public String getGestion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.params.plafond</code>.
     */
    public void setPlafond(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.params.plafond</code>.
     */
    public Long getPlafond() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.params.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.params.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.params.seuil_alerte</code>.
     */
    public void setSeuilAlerte(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.params.seuil_alerte</code>.
     */
    public Long getSeuilAlerte() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long, Boolean, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long, Boolean, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Params.PARAMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Params.PARAMS.GESTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Params.PARAMS.PLAFOND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Params.PARAMS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Params.PARAMS.SEUIL_ALERTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPlafond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSeuilAlerte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPlafond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSeuilAlerte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value2(String value) {
        setGestion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value3(Long value) {
        setPlafond(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value4(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value5(Long value) {
        setSeuilAlerte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord values(Long value1, String value2, Long value3, Boolean value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParamsRecord
     */
    public ParamsRecord() {
        super(Params.PARAMS);
    }

    /**
     * Create a detached, initialised ParamsRecord
     */
    public ParamsRecord(Long id, String gestion, Long plafond, Boolean isDeleted, Long seuilAlerte) {
        super(Params.PARAMS);

        set(0, id);
        set(1, gestion);
        set(2, plafond);
        set(3, isDeleted);
        set(4, seuilAlerte);
    }
}
