/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.Personnel;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonnelRecord extends TableRecordImpl<PersonnelRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 787232397;

    /**
     * Setter for <code>public.personnel.matricule</code>.
     */
    public void setMatricule(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.personnel.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.personnel.nom</code>.
     */
    public void setNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.personnel.nom</code>.
     */
    public String getNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.personnel.prenom</code>.
     */
    public void setPrenom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.personnel.prenom</code>.
     */
    public String getPrenom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.personnel.sexe</code>.
     */
    public void setSexe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.personnel.sexe</code>.
     */
    public String getSexe() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Personnel.PERSONNEL.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Personnel.PERSONNEL.NOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Personnel.PERSONNEL.PRENOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Personnel.PERSONNEL.SEXE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelRecord value1(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelRecord value2(String value) {
        setNom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelRecord value3(String value) {
        setPrenom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelRecord value4(String value) {
        setSexe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonnelRecord
     */
    public PersonnelRecord() {
        super(Personnel.PERSONNEL);
    }

    /**
     * Create a detached, initialised PersonnelRecord
     */
    public PersonnelRecord(String matricule, String nom, String prenom, String sexe) {
        super(Personnel.PERSONNEL);

        set(0, matricule);
        set(1, nom);
        set(2, prenom);
        set(3, sexe);
    }
}
