/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Region;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionRecord extends UpdatableRecordImpl<RegionRecord> implements Record5<Long, String, String, Timestamp, Boolean> {

    private static final long serialVersionUID = 525907652;

    /**
     * Setter for <code>public.region.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.region.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.region.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.region.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.region.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.region.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.region.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.region.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.region.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.region.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Region.REGION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Region.REGION.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Region.REGION.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Region.REGION.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Region.REGION.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord value3(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord value4(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegionRecord values(Long value1, String value2, String value3, Timestamp value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegionRecord
     */
    public RegionRecord() {
        super(Region.REGION);
    }

    /**
     * Create a detached, initialised RegionRecord
     */
    public RegionRecord(Long id, String libelle, String whoDone, Timestamp whenDone, Boolean isDeleted) {
        super(Region.REGION);

        set(0, id);
        set(1, libelle);
        set(2, whoDone);
        set(3, whenDone);
        set(4, isDeleted);
    }
}
