/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.StructurePartenaire;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StructurePartenaireRecord extends UpdatableRecordImpl<StructurePartenaireRecord> implements Record7<Long, String, String, Timestamp, Boolean, String, Long> {

    private static final long serialVersionUID = 751288061;

    /**
     * Setter for <code>public.structure_partenaire.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.structure_partenaire.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.structure_partenaire.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.structure_partenaire.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.structure_partenaire.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.structure_partenaire.telephone</code>.
     */
    public void setTelephone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.structure_partenaire.region</code>.
     */
    public void setRegion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.structure_partenaire.region</code>.
     */
    public Long getRegion() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Timestamp, Boolean, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Timestamp, Boolean, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return StructurePartenaire.STRUCTURE_PARTENAIRE.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value3(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value4(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value6(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord value7(Long value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaireRecord values(Long value1, String value2, String value3, Timestamp value4, Boolean value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StructurePartenaireRecord
     */
    public StructurePartenaireRecord() {
        super(StructurePartenaire.STRUCTURE_PARTENAIRE);
    }

    /**
     * Create a detached, initialised StructurePartenaireRecord
     */
    public StructurePartenaireRecord(Long id, String libelle, String whoDone, Timestamp whenDone, Boolean isDeleted, String telephone, Long region) {
        super(StructurePartenaire.STRUCTURE_PARTENAIRE);

        set(0, id);
        set(1, libelle);
        set(2, whoDone);
        set(3, whenDone);
        set(4, isDeleted);
        set(5, telephone);
        set(6, region);
    }
}
