/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.TypePrestation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePrestationRecord extends UpdatableRecordImpl<TypePrestationRecord> implements Record4<Long, String, String, Boolean> {

    private static final long serialVersionUID = -1996438789;

    /**
     * Setter for <code>public.type_prestation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.type_prestation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.type_prestation.prestation</code>.
     */
    public void setPrestation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.type_prestation.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.type_prestation.couverture</code>.
     */
    public void setCouverture(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.type_prestation.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.type_prestation.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.type_prestation.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TypePrestation.TYPE_PRESTATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TypePrestation.TYPE_PRESTATION.PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TypePrestation.TYPE_PRESTATION.COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TypePrestation.TYPE_PRESTATION.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value2(String value) {
        setPrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value3(String value) {
        setCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value4(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord values(Long value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TypePrestationRecord
     */
    public TypePrestationRecord() {
        super(TypePrestation.TYPE_PRESTATION);
    }

    /**
     * Create a detached, initialised TypePrestationRecord
     */
    public TypePrestationRecord(Long id, String prestation, String couverture, Boolean onDeleted) {
        super(TypePrestation.TYPE_PRESTATION);

        set(0, id);
        set(1, prestation);
        set(2, couverture);
        set(3, onDeleted);
    }
}
