/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VAdherentAyantDroit;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentAyantDroitRecord extends TableRecordImpl<VAdherentAyantDroitRecord> {

    private static final long serialVersionUID = 851379217;

    /**
     * Setter for <code>public.v_adherent_ayant_droit.id_adherent</code>.
     */
    public void setIdAdherent(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.id_adherent</code>.
     */
    public Long getIdAdherent() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.sexe</code>.
     */
    public void setSexe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.sexe</code>.
     */
    public String getSexe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.fonction</code>.
     */
    public void setFonction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.fonction</code>.
     */
    public String getFonction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.date_naiss_adherent</code>.
     */
    public void setDateNaissAdherent(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.date_naiss_adherent</code>.
     */
    public Timestamp getDateNaissAdherent() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.date_prise_service</code>.
     */
    public void setDatePriseService(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.date_prise_service</code>.
     */
    public Timestamp getDatePriseService() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.picture_adherent</code>.
     */
    public void setPictureAdherent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.picture_adherent</code>.
     */
    public String getPictureAdherent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.direction</code>.
     */
    public void setDirection(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.direction</code>.
     */
    public Long getDirection() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.division</code>.
     */
    public void setDivision(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.division</code>.
     */
    public Long getDivision() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.service</code>.
     */
    public void setService(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.service</code>.
     */
    public Long getService() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.telephone</code>.
     */
    public void setTelephone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.matricule</code>.
     */
    public void setMatricule(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.structure</code>.
     */
    public void setStructure(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.structure</code>.
     */
    public String getStructure() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.structure_sigle</code>.
     */
    public void setStructureSigle(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.structure_sigle</code>.
     */
    public String getStructureSigle() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.code_programme</code>.
     */
    public void setCodeProgramme(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.code_programme</code>.
     */
    public String getCodeProgramme() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.categorie</code>.
     */
    public void setCategorie(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.id_ayant_droit</code>.
     */
    public void setIdAyantDroit(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.id_ayant_droit</code>.
     */
    public Long getIdAyantDroit() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.nom_ay</code>.
     */
    public void setNomAy(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.nom_ay</code>.
     */
    public String getNomAy() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.date_naiss_ayant_droit</code>.
     */
    public void setDateNaissAyantDroit(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.date_naiss_ayant_droit</code>.
     */
    public Timestamp getDateNaissAyantDroit() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.age_adherent</code>.
     */
    public void setAgeAdherent(Double value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.age_adherent</code>.
     */
    public Double getAgeAdherent() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.age</code>.
     */
    public void setAge(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.age</code>.
     */
    public Double getAge() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.adherent</code>.
     */
    public void setAdherent(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.adherent</code>.
     */
    public Long getAdherent() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.picture_ayant_droit</code>.
     */
    public void setPictureAyantDroit(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.picture_ayant_droit</code>.
     */
    public String getPictureAyantDroit() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.lien</code>.
     */
    public void setLien(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.lien</code>.
     */
    public String getLien() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.v_adherent_ayant_droit.genre</code>.
     */
    public void setGenre(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.v_adherent_ayant_droit.genre</code>.
     */
    public String getGenre() {
        return (String) get(25);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAdherentAyantDroitRecord
     */
    public VAdherentAyantDroitRecord() {
        super(VAdherentAyantDroit.V_ADHERENT_AYANT_DROIT);
    }

    /**
     * Create a detached, initialised VAdherentAyantDroitRecord
     */
    public VAdherentAyantDroitRecord(Long idAdherent, String nomAd, String prenomAd, String sexe, String fonction, Timestamp dateNaissAdherent, Timestamp datePriseService, String pictureAdherent, Long direction, Long division, Long service, String telephone, String matricule, String structure, String structureSigle, String codeProgramme, String categorie, Long idAyantDroit, String nomAy, Timestamp dateNaissAyantDroit, Double ageAdherent, Double age, Long adherent, String pictureAyantDroit, String lien, String genre) {
        super(VAdherentAyantDroit.V_ADHERENT_AYANT_DROIT);

        set(0, idAdherent);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, sexe);
        set(4, fonction);
        set(5, dateNaissAdherent);
        set(6, datePriseService);
        set(7, pictureAdherent);
        set(8, direction);
        set(9, division);
        set(10, service);
        set(11, telephone);
        set(12, matricule);
        set(13, structure);
        set(14, structureSigle);
        set(15, codeProgramme);
        set(16, categorie);
        set(17, idAyantDroit);
        set(18, nomAy);
        set(19, dateNaissAyantDroit);
        set(20, ageAdherent);
        set(21, age);
        set(22, adherent);
        set(23, pictureAyantDroit);
        set(24, lien);
        set(25, genre);
    }
}
