/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import models.tables.VCumuleByStructure;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCumuleByStructureRecord extends TableRecordImpl<VCumuleByStructureRecord> implements Record3<String, BigDecimal, String> {

    private static final long serialVersionUID = 1949085098;

    /**
     * Setter for <code>public.v_cumule_by_structure.structure</code>.
     */
    public void setStructure(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_cumule_by_structure.structure</code>.
     */
    public String getStructure() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.v_cumule_by_structure.total_annuel</code>.
     */
    public void setTotalAnnuel(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_cumule_by_structure.total_annuel</code>.
     */
    public BigDecimal getTotalAnnuel() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.v_cumule_by_structure.annee</code>.
     */
    public void setAnnee(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_cumule_by_structure.annee</code>.
     */
    public String getAnnee() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, BigDecimal, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, BigDecimal, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VCumuleByStructure.V_CUMULE_BY_STRUCTURE.STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return VCumuleByStructure.V_CUMULE_BY_STRUCTURE.TOTAL_ANNUEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VCumuleByStructure.V_CUMULE_BY_STRUCTURE.ANNEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getTotalAnnuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getTotalAnnuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCumuleByStructureRecord value1(String value) {
        setStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCumuleByStructureRecord value2(BigDecimal value) {
        setTotalAnnuel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCumuleByStructureRecord value3(String value) {
        setAnnee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCumuleByStructureRecord values(String value1, BigDecimal value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VCumuleByStructureRecord
     */
    public VCumuleByStructureRecord() {
        super(VCumuleByStructure.V_CUMULE_BY_STRUCTURE);
    }

    /**
     * Create a detached, initialised VCumuleByStructureRecord
     */
    public VCumuleByStructureRecord(String structure, BigDecimal totalAnnuel, String annee) {
        super(VCumuleByStructure.V_CUMULE_BY_STRUCTURE);

        set(0, structure);
        set(1, totalAnnuel);
        set(2, annee);
    }
}
