/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.VNbrBenefiaireParPrestation;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBenefiaireParPrestationRecord extends TableRecordImpl<VNbrBenefiaireParPrestationRecord> implements Record4<String, Long, Long, String> {

    private static final long serialVersionUID = -580930750;

    /**
     * Setter for <code>public.v_nbr_benefiaire_par_prestation.prestation</code>.
     */
    public void setPrestation(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_nbr_benefiaire_par_prestation.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.v_nbr_benefiaire_par_prestation.nbr_adherent_ayant_beneficier</code>.
     */
    public void setNbrAdherentAyantBeneficier(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_nbr_benefiaire_par_prestation.nbr_adherent_ayant_beneficier</code>.
     */
    public Long getNbrAdherentAyantBeneficier() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.v_nbr_benefiaire_par_prestation.nbr_prestation_effectuer</code>.
     */
    public void setNbrPrestationEffectuer(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_nbr_benefiaire_par_prestation.nbr_prestation_effectuer</code>.
     */
    public Long getNbrPrestationEffectuer() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.v_nbr_benefiaire_par_prestation.annee</code>.
     */
    public void setAnnee(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_nbr_benefiaire_par_prestation.annee</code>.
     */
    public String getAnnee() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Long, Long, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Long, Long, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION.PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION.NBR_ADHERENT_AYANT_BENEFICIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION.NBR_PRESTATION_EFFECTUER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION.ANNEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNbrAdherentAyantBeneficier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getNbrPrestationEffectuer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNbrAdherentAyantBeneficier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getNbrPrestationEffectuer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestationRecord value1(String value) {
        setPrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestationRecord value2(Long value) {
        setNbrAdherentAyantBeneficier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestationRecord value3(Long value) {
        setNbrPrestationEffectuer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestationRecord value4(String value) {
        setAnnee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestationRecord values(String value1, Long value2, Long value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VNbrBenefiaireParPrestationRecord
     */
    public VNbrBenefiaireParPrestationRecord() {
        super(VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION);
    }

    /**
     * Create a detached, initialised VNbrBenefiaireParPrestationRecord
     */
    public VNbrBenefiaireParPrestationRecord(String prestation, Long nbrAdherentAyantBeneficier, Long nbrPrestationEffectuer, String annee) {
        super(VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION);

        set(0, prestation);
        set(1, nbrAdherentAyantBeneficier);
        set(2, nbrPrestationEffectuer);
        set(3, annee);
    }
}
