/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.VReglementGlobale;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementGlobaleRecord extends TableRecordImpl<VReglementGlobaleRecord> implements Record5<String, String, String, Long, String> {

    private static final long serialVersionUID = 1971277958;

    /**
     * Setter for <code>public.v_reglement_globale.matricule</code>.
     */
    public void setMatricule(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_reglement_globale.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.v_reglement_globale.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_reglement_globale.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_reglement_globale.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_reglement_globale.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_reglement_globale.total_annuel</code>.
     */
    public void setTotalAnnuel(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_reglement_globale.total_annuel</code>.
     */
    public Long getTotalAnnuel() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.v_reglement_globale.annee</code>.
     */
    public void setAnnee(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_reglement_globale.annee</code>.
     */
    public String getAnnee() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Long, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VReglementGlobale.V_REGLEMENT_GLOBALE.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VReglementGlobale.V_REGLEMENT_GLOBALE.NOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VReglementGlobale.V_REGLEMENT_GLOBALE.PRENOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return VReglementGlobale.V_REGLEMENT_GLOBALE.TOTAL_ANNUEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VReglementGlobale.V_REGLEMENT_GLOBALE.ANNEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getTotalAnnuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getTotalAnnuel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord value1(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord value2(String value) {
        setNomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord value3(String value) {
        setPrenomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord value4(Long value) {
        setTotalAnnuel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord value5(String value) {
        setAnnee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobaleRecord values(String value1, String value2, String value3, Long value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VReglementGlobaleRecord
     */
    public VReglementGlobaleRecord() {
        super(VReglementGlobale.V_REGLEMENT_GLOBALE);
    }

    /**
     * Create a detached, initialised VReglementGlobaleRecord
     */
    public VReglementGlobaleRecord(String matricule, String nomAd, String prenomAd, Long totalAnnuel, String annee) {
        super(VReglementGlobale.V_REGLEMENT_GLOBALE);

        set(0, matricule);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, totalAnnuel);
        set(4, annee);
    }
}
