/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VReglement;

import org.jooq.Field;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementRecord extends TableRecordImpl<VReglementRecord> implements Record22<Long, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, Boolean, String, String, String, String, String, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = -141943841;

    /**
     * Setter for <code>public.v_reglement.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_reglement.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_reglement.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_reglement.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_reglement.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_reglement.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_reglement.id_adherent</code>.
     */
    public void setIdAdherent(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_reglement.id_adherent</code>.
     */
    public Long getIdAdherent() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.v_reglement.matricule</code>.
     */
    public void setMatricule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_reglement.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_reglement.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_reglement.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_reglement.structure</code>.
     */
    public void setStructure(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_reglement.structure</code>.
     */
    public String getStructure() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_reglement.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_reglement.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.v_reglement.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_reglement.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_reglement.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_reglement.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.v_reglement.annee</code>.
     */
    public void setAnnee(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_reglement.annee</code>.
     */
    public String getAnnee() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_reglement.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_reglement.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.v_reglement.prestation</code>.
     */
    public void setPrestation(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_reglement.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_reglement.couverture</code>.
     */
    public void setCouverture(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_reglement.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_reglement.nom_ay</code>.
     */
    public void setNomAy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_reglement.nom_ay</code>.
     */
    public String getNomAy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_reglement.lien</code>.
     */
    public void setLien(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_reglement.lien</code>.
     */
    public String getLien() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_reglement.genre</code>.
     */
    public void setGenre(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_reglement.genre</code>.
     */
    public String getGenre() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_reglement.ayant_droit</code>.
     */
    public void setAyantDroit(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_reglement.ayant_droit</code>.
     */
    public Long getAyantDroit() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.v_reglement.montant_total</code>.
     */
    public void setMontantTotal(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_reglement.montant_total</code>.
     */
    public Long getMontantTotal() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.v_reglement.montant_reglement</code>.
     */
    public void setMontantReglement(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_reglement.montant_reglement</code>.
     */
    public Long getMontantReglement() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.v_reglement.montant_paye</code>.
     */
    public void setMontantPaye(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_reglement.montant_paye</code>.
     */
    public Long getMontantPaye() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.v_reglement.id_structure</code>.
     */
    public void setIdStructure(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_reglement.id_structure</code>.
     */
    public Long getIdStructure() {
        return (Long) get(21);
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, Boolean, String, String, String, String, String, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, Boolean, String, String, String, String, String, Long, Long, Long, Long, Long> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VReglement.V_REGLEMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VReglement.V_REGLEMENT.NOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VReglement.V_REGLEMENT.PRENOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return VReglement.V_REGLEMENT.ID_ADHERENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VReglement.V_REGLEMENT.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VReglement.V_REGLEMENT.REF_FACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VReglement.V_REGLEMENT.STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VReglement.V_REGLEMENT.DATE_PAYEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VReglement.V_REGLEMENT.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return VReglement.V_REGLEMENT.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VReglement.V_REGLEMENT.ANNEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return VReglement.V_REGLEMENT.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VReglement.V_REGLEMENT.PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return VReglement.V_REGLEMENT.COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VReglement.V_REGLEMENT.NOM_AY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return VReglement.V_REGLEMENT.LIEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return VReglement.V_REGLEMENT.GENRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return VReglement.V_REGLEMENT.AYANT_DROIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field19() {
        return VReglement.V_REGLEMENT.MONTANT_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field20() {
        return VReglement.V_REGLEMENT.MONTANT_REGLEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field21() {
        return VReglement.V_REGLEMENT.MONTANT_PAYE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field22() {
        return VReglement.V_REGLEMENT.ID_STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getIdAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getNomAy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getLien();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getGenre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getAyantDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component19() {
        return getMontantTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component20() {
        return getMontantReglement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component21() {
        return getMontantPaye();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component22() {
        return getIdStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getIdAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getNomAy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getLien();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getGenre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getAyantDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value19() {
        return getMontantTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value20() {
        return getMontantReglement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value21() {
        return getMontantPaye();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value22() {
        return getIdStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value2(String value) {
        setNomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value3(String value) {
        setPrenomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value4(Long value) {
        setIdAdherent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value5(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value6(String value) {
        setRefFacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value7(String value) {
        setStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value8(Timestamp value) {
        setDatePayement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value9(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value10(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value11(String value) {
        setAnnee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value12(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value13(String value) {
        setPrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value14(String value) {
        setCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value15(String value) {
        setNomAy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value16(String value) {
        setLien(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value17(String value) {
        setGenre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value18(Long value) {
        setAyantDroit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value19(Long value) {
        setMontantTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value20(Long value) {
        setMontantReglement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value21(Long value) {
        setMontantPaye(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord value22(Long value) {
        setIdStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementRecord values(Long value1, String value2, String value3, Long value4, String value5, String value6, String value7, Timestamp value8, String value9, Timestamp value10, String value11, Boolean value12, String value13, String value14, String value15, String value16, String value17, Long value18, Long value19, Long value20, Long value21, Long value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VReglementRecord
     */
    public VReglementRecord() {
        super(VReglement.V_REGLEMENT);
    }

    /**
     * Create a detached, initialised VReglementRecord
     */
    public VReglementRecord(Long id, String nomAd, String prenomAd, Long idAdherent, String matricule, String refFacture, String structure, Timestamp datePayement, String whoDone, Timestamp whenDone, String annee, Boolean onDeleted, String prestation, String couverture, String nomAy, String lien, String genre, Long ayantDroit, Long montantTotal, Long montantReglement, Long montantPaye, Long idStructure) {
        super(VReglement.V_REGLEMENT);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, idAdherent);
        set(4, matricule);
        set(5, refFacture);
        set(6, structure);
        set(7, datePayement);
        set(8, whoDone);
        set(9, whenDone);
        set(10, annee);
        set(11, onDeleted);
        set(12, prestation);
        set(13, couverture);
        set(14, nomAy);
        set(15, lien);
        set(16, genre);
        set(17, ayantDroit);
        set(18, montantTotal);
        set(19, montantReglement);
        set(20, montantPaye);
        set(21, idStructure);
    }
}
