/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.AdherentRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adherent extends TableImpl<AdherentRecord> {

    private static final long serialVersionUID = -675581125;

    /**
     * The reference instance of <code>public.adherent</code>
     */
    public static final Adherent ADHERENT = new Adherent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdherentRecord> getRecordType() {
        return AdherentRecord.class;
    }

    /**
     * The column <code>public.adherent.id</code>.
     */
    public final TableField<AdherentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('adherent_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.adherent.nom_ad</code>.
     */
    public final TableField<AdherentRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.prenom_ad</code>.
     */
    public final TableField<AdherentRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.fonction</code>.
     */
    public final TableField<AdherentRecord, String> FONCTION = createField("fonction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.date_naiss</code>.
     */
    public final TableField<AdherentRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.adherent.date_prise_service</code>.
     */
    public final TableField<AdherentRecord, Timestamp> DATE_PRISE_SERVICE = createField("date_prise_service", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.adherent.picture</code>.
     */
    public final TableField<AdherentRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.when_done</code>.
     */
    public final TableField<AdherentRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.adherent.who_done</code>.
     */
    public final TableField<AdherentRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.on_deleted</code>.
     */
    public final TableField<AdherentRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.adherent.direction</code>.
     */
    public final TableField<AdherentRecord, Long> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.adherent.division</code>.
     */
    public final TableField<AdherentRecord, Long> DIVISION = createField("division", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.adherent.service</code>.
     */
    public final TableField<AdherentRecord, Long> SERVICE = createField("service", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.adherent.telephone</code>.
     */
    public final TableField<AdherentRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.matricule</code>.
     */
    public final TableField<AdherentRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.structure</code>.
     */
    public final TableField<AdherentRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.structure_sigle</code>.
     */
    public final TableField<AdherentRecord, String> STRUCTURE_SIGLE = createField("structure_sigle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.code_programme</code>.
     */
    public final TableField<AdherentRecord, String> CODE_PROGRAMME = createField("code_programme", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.categorie</code>.
     */
    public final TableField<AdherentRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.sexe</code>.
     */
    public final TableField<AdherentRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.mat</code>.
     */
    public final TableField<AdherentRecord, Long> MAT = createField("mat", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.adherent.email</code>.
     */
    public final TableField<AdherentRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.adherent.is_member</code>.
     */
    public final TableField<AdherentRecord, Boolean> IS_MEMBER = createField("is_member", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.adherent.is_ok_for_printing</code>.
     */
    public final TableField<AdherentRecord, Boolean> IS_OK_FOR_PRINTING = createField("is_ok_for_printing", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.adherent</code> table reference
     */
    public Adherent() {
        this(DSL.name("adherent"), null);
    }

    /**
     * Create an aliased <code>public.adherent</code> table reference
     */
    public Adherent(String alias) {
        this(DSL.name(alias), ADHERENT);
    }

    /**
     * Create an aliased <code>public.adherent</code> table reference
     */
    public Adherent(Name alias) {
        this(alias, ADHERENT);
    }

    private Adherent(Name alias, Table<AdherentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Adherent(Name alias, Table<AdherentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ADHERENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AdherentRecord, Long> getIdentity() {
        return Keys.IDENTITY_ADHERENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AdherentRecord> getPrimaryKey() {
        return Keys.ADHERENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AdherentRecord>> getKeys() {
        return Arrays.<UniqueKey<AdherentRecord>>asList(Keys.ADHERENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AdherentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AdherentRecord, ?>>asList(Keys.ADHERENT__PROGAM_FKY, Keys.ADHERENT__CATEGORIE_FKY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Adherent as(String alias) {
        return new Adherent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Adherent as(Name alias) {
        return new Adherent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Adherent rename(String name) {
        return new Adherent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adherent rename(Name name) {
        return new Adherent(name, null);
    }
}
