/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.AyantDroitRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AyantDroit extends TableImpl<AyantDroitRecord> {

    private static final long serialVersionUID = -420679439;

    /**
     * The reference instance of <code>public.ayant_droit</code>
     */
    public static final AyantDroit AYANT_DROIT = new AyantDroit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AyantDroitRecord> getRecordType() {
        return AyantDroitRecord.class;
    }

    /**
     * The column <code>public.ayant_droit.id</code>.
     */
    public final TableField<AyantDroitRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ayant_droit_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.ayant_droit.nom_ay</code>.
     */
    public final TableField<AyantDroitRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ayant_droit.date_naiss</code>.
     */
    public final TableField<AyantDroitRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.ayant_droit.adherent</code>.
     */
    public final TableField<AyantDroitRecord, Long> ADHERENT = createField("adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.ayant_droit.when_done</code>.
     */
    public final TableField<AyantDroitRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.ayant_droit.who_done</code>.
     */
    public final TableField<AyantDroitRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ayant_droit.on_deleted</code>.
     */
    public final TableField<AyantDroitRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.ayant_droit.picture</code>.
     */
    public final TableField<AyantDroitRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ayant_droit.lien</code>.
     */
    public final TableField<AyantDroitRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ayant_droit.genre</code>.
     */
    public final TableField<AyantDroitRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ayant_droit.is_ok_for_printing</code>.
     */
    public final TableField<AyantDroitRecord, Boolean> IS_OK_FOR_PRINTING = createField("is_ok_for_printing", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.ayant_droit</code> table reference
     */
    public AyantDroit() {
        this(DSL.name("ayant_droit"), null);
    }

    /**
     * Create an aliased <code>public.ayant_droit</code> table reference
     */
    public AyantDroit(String alias) {
        this(DSL.name(alias), AYANT_DROIT);
    }

    /**
     * Create an aliased <code>public.ayant_droit</code> table reference
     */
    public AyantDroit(Name alias) {
        this(alias, AYANT_DROIT);
    }

    private AyantDroit(Name alias, Table<AyantDroitRecord> aliased) {
        this(alias, aliased, null);
    }

    private AyantDroit(Name alias, Table<AyantDroitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AYANT_DROIT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AyantDroitRecord, Long> getIdentity() {
        return Keys.IDENTITY_AYANT_DROIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AyantDroitRecord> getPrimaryKey() {
        return Keys.AYANT_DROIT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AyantDroitRecord>> getKeys() {
        return Arrays.<UniqueKey<AyantDroitRecord>>asList(Keys.AYANT_DROIT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AyantDroitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AyantDroitRecord, ?>>asList(Keys.AYANT_DROIT__ADHERENT_FKY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AyantDroit as(String alias) {
        return new AyantDroit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AyantDroit as(Name alias) {
        return new AyantDroit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AyantDroit rename(String name) {
        return new AyantDroit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AyantDroit rename(Name name) {
        return new AyantDroit(name, null);
    }
}
