/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.CategorieRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categorie extends TableImpl<CategorieRecord> {

    private static final long serialVersionUID = 2086011086;

    /**
     * The reference instance of <code>public.categorie</code>
     */
    public static final Categorie CATEGORIE = new Categorie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategorieRecord> getRecordType() {
        return CategorieRecord.class;
    }

    /**
     * The column <code>public.categorie.id</code>.
     */
    public final TableField<CategorieRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('categorie_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.categorie.code</code>.
     */
    public final TableField<CategorieRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.categorie.libelle</code>.
     */
    public final TableField<CategorieRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.categorie.when_done</code>.
     */
    public final TableField<CategorieRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.categorie.who_done</code>.
     */
    public final TableField<CategorieRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.categorie.on_deleted</code>.
     */
    public final TableField<CategorieRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.categorie</code> table reference
     */
    public Categorie() {
        this(DSL.name("categorie"), null);
    }

    /**
     * Create an aliased <code>public.categorie</code> table reference
     */
    public Categorie(String alias) {
        this(DSL.name(alias), CATEGORIE);
    }

    /**
     * Create an aliased <code>public.categorie</code> table reference
     */
    public Categorie(Name alias) {
        this(alias, CATEGORIE);
    }

    private Categorie(Name alias, Table<CategorieRecord> aliased) {
        this(alias, aliased, null);
    }

    private Categorie(Name alias, Table<CategorieRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CATEGORIE_PKEY, Indexes.CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CategorieRecord, Long> getIdentity() {
        return Keys.IDENTITY_CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategorieRecord> getPrimaryKey() {
        return Keys.CATEGORIE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategorieRecord>> getKeys() {
        return Arrays.<UniqueKey<CategorieRecord>>asList(Keys.CATEGORIE_PKEY, Keys.CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Categorie as(String alias) {
        return new Categorie(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Categorie as(Name alias) {
        return new Categorie(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Categorie rename(String name) {
        return new Categorie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Categorie rename(Name name) {
        return new Categorie(name, null);
    }
}
