/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.ClassCompteRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassCompte extends TableImpl<ClassCompteRecord> {

    private static final long serialVersionUID = -363898296;

    /**
     * The reference instance of <code>public.class_compte</code>
     */
    public static final ClassCompte CLASS_COMPTE = new ClassCompte();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassCompteRecord> getRecordType() {
        return ClassCompteRecord.class;
    }

    /**
     * The column <code>public.class_compte.id</code>.
     */
    public final TableField<ClassCompteRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('class_compte_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.class_compte.categorie</code>.
     */
    public final TableField<ClassCompteRecord, Long> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.class_compte.libelle_compte</code>.
     */
    public final TableField<ClassCompteRecord, String> LIBELLE_COMPTE = createField("libelle_compte", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.class_compte.description</code>.
     */
    public final TableField<ClassCompteRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.class_compte.is_deleted</code>.
     */
    public final TableField<ClassCompteRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.class_compte.who_done</code>.
     */
    public final TableField<ClassCompteRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.class_compte.when_done</code>.
     */
    public final TableField<ClassCompteRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.class_compte.is_for_budget</code>.
     */
    public final TableField<ClassCompteRecord, Boolean> IS_FOR_BUDGET = createField("is_for_budget", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.class_compte.num_compte</code>.
     */
    public final TableField<ClassCompteRecord, Long> NUM_COMPTE = createField("num_compte", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.class_compte</code> table reference
     */
    public ClassCompte() {
        this(DSL.name("class_compte"), null);
    }

    /**
     * Create an aliased <code>public.class_compte</code> table reference
     */
    public ClassCompte(String alias) {
        this(DSL.name(alias), CLASS_COMPTE);
    }

    /**
     * Create an aliased <code>public.class_compte</code> table reference
     */
    public ClassCompte(Name alias) {
        this(alias, CLASS_COMPTE);
    }

    private ClassCompte(Name alias, Table<ClassCompteRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClassCompte(Name alias, Table<ClassCompteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLASS_COMPTE_PKEY, Indexes.NUM_COMPTE_UNIK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClassCompteRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLASS_COMPTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassCompteRecord> getPrimaryKey() {
        return Keys.CLASS_COMPTE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassCompteRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassCompteRecord>>asList(Keys.CLASS_COMPTE_PKEY, Keys.NUM_COMPTE_UNIK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClassCompteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClassCompteRecord, ?>>asList(Keys.CLASS_COMPTE__FKEY_CATEGORIE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompte as(String alias) {
        return new ClassCompte(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassCompte as(Name alias) {
        return new ClassCompte(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassCompte rename(String name) {
        return new ClassCompte(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassCompte rename(Name name) {
        return new ClassCompte(name, null);
    }
}
