/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.ConnexionRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Connexion extends TableImpl<ConnexionRecord> {

    private static final long serialVersionUID = -926794731;

    /**
     * The reference instance of <code>public.connexion</code>
     */
    public static final Connexion CONNEXION = new Connexion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConnexionRecord> getRecordType() {
        return ConnexionRecord.class;
    }

    /**
     * The column <code>public.connexion.id</code>.
     */
    public final TableField<ConnexionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('connexion_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.connexion.user</code>.
     */
    public final TableField<ConnexionRecord, String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.connexion.profil</code>.
     */
    public final TableField<ConnexionRecord, String> PROFIL = createField("profil", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.connexion.when_down</code>.
     */
    public final TableField<ConnexionRecord, Timestamp> WHEN_DOWN = createField("when_down", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.connexion</code> table reference
     */
    public Connexion() {
        this(DSL.name("connexion"), null);
    }

    /**
     * Create an aliased <code>public.connexion</code> table reference
     */
    public Connexion(String alias) {
        this(DSL.name(alias), CONNEXION);
    }

    /**
     * Create an aliased <code>public.connexion</code> table reference
     */
    public Connexion(Name alias) {
        this(alias, CONNEXION);
    }

    private Connexion(Name alias, Table<ConnexionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Connexion(Name alias, Table<ConnexionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONNEXION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ConnexionRecord, Long> getIdentity() {
        return Keys.IDENTITY_CONNEXION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConnexionRecord> getPrimaryKey() {
        return Keys.CONNEXION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConnexionRecord>> getKeys() {
        return Arrays.<UniqueKey<ConnexionRecord>>asList(Keys.CONNEXION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Connexion as(String alias) {
        return new Connexion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Connexion as(Name alias) {
        return new Connexion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Connexion rename(String name) {
        return new Connexion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Connexion rename(Name name) {
        return new Connexion(name, null);
    }
}
