/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.DepenseRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Depense extends TableImpl<DepenseRecord> {

    private static final long serialVersionUID = -1885354277;

    /**
     * The reference instance of <code>public.depense</code>
     */
    public static final Depense DEPENSE = new Depense();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepenseRecord> getRecordType() {
        return DepenseRecord.class;
    }

    /**
     * The column <code>public.depense.id</code>.
     */
    public final TableField<DepenseRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('depense_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.depense.ref_depense</code>.
     */
    public final TableField<DepenseRecord, String> REF_DEPENSE = createField("ref_depense", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.depense.date_depense</code>.
     */
    public final TableField<DepenseRecord, Timestamp> DATE_DEPENSE = createField("date_depense", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.depense.is_deleted</code>.
     */
    public final TableField<DepenseRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.depense.who_done</code>.
     */
    public final TableField<DepenseRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.depense.when_done</code>.
     */
    public final TableField<DepenseRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.depense.last_update</code>.
     */
    public final TableField<DepenseRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.depense</code> table reference
     */
    public Depense() {
        this(DSL.name("depense"), null);
    }

    /**
     * Create an aliased <code>public.depense</code> table reference
     */
    public Depense(String alias) {
        this(DSL.name(alias), DEPENSE);
    }

    /**
     * Create an aliased <code>public.depense</code> table reference
     */
    public Depense(Name alias) {
        this(alias, DEPENSE);
    }

    private Depense(Name alias, Table<DepenseRecord> aliased) {
        this(alias, aliased, null);
    }

    private Depense(Name alias, Table<DepenseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_DEPENSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DepenseRecord, Long> getIdentity() {
        return Keys.IDENTITY_DEPENSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DepenseRecord> getPrimaryKey() {
        return Keys.PRIMARY_DEPENSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DepenseRecord>> getKeys() {
        return Arrays.<UniqueKey<DepenseRecord>>asList(Keys.PRIMARY_DEPENSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Depense as(String alias) {
        return new Depense(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Depense as(Name alias) {
        return new Depense(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Depense rename(String name) {
        return new Depense(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Depense rename(Name name) {
        return new Depense(name, null);
    }
}
