/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.PersonnelRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personnel extends TableImpl<PersonnelRecord> {

    private static final long serialVersionUID = 614355844;

    /**
     * The reference instance of <code>public.personnel</code>
     */
    public static final Personnel PERSONNEL = new Personnel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonnelRecord> getRecordType() {
        return PersonnelRecord.class;
    }

    /**
     * The column <code>public.personnel.matricule</code>.
     */
    public final TableField<PersonnelRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.personnel.nom</code>.
     */
    public final TableField<PersonnelRecord, String> NOM = createField("nom", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.personnel.prenom</code>.
     */
    public final TableField<PersonnelRecord, String> PRENOM = createField("prenom", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.personnel.sexe</code>.
     */
    public final TableField<PersonnelRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.personnel</code> table reference
     */
    public Personnel() {
        this(DSL.name("personnel"), null);
    }

    /**
     * Create an aliased <code>public.personnel</code> table reference
     */
    public Personnel(String alias) {
        this(DSL.name(alias), PERSONNEL);
    }

    /**
     * Create an aliased <code>public.personnel</code> table reference
     */
    public Personnel(Name alias) {
        this(alias, PERSONNEL);
    }

    private Personnel(Name alias, Table<PersonnelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Personnel(Name alias, Table<PersonnelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personnel as(String alias) {
        return new Personnel(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personnel as(Name alias) {
        return new Personnel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Personnel rename(String name) {
        return new Personnel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Personnel rename(Name name) {
        return new Personnel(name, null);
    }
}
