/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.ReglementDetailRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReglementDetail extends TableImpl<ReglementDetailRecord> {

    private static final long serialVersionUID = -274677113;

    /**
     * The reference instance of <code>public.reglement_detail</code>
     */
    public static final ReglementDetail REGLEMENT_DETAIL = new ReglementDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReglementDetailRecord> getRecordType() {
        return ReglementDetailRecord.class;
    }

    /**
     * The column <code>public.reglement_detail.id</code>.
     */
    public final TableField<ReglementDetailRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('reglement_detail_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.reglement_detail.reglement</code>.
     */
    public final TableField<ReglementDetailRecord, Long> REGLEMENT = createField("reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.reglement_detail.intitule</code>.
     */
    public final TableField<ReglementDetailRecord, String> INTITULE = createField("intitule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.reglement_detail.montant</code>.
     */
    public final TableField<ReglementDetailRecord, Long> MONTANT = createField("montant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.reglement_detail.who_done</code>.
     */
    public final TableField<ReglementDetailRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.reglement_detail.when_done</code>.
     */
    public final TableField<ReglementDetailRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.reglement_detail.on_deleted</code>.
     */
    public final TableField<ReglementDetailRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.reglement_detail.last_update</code>.
     */
    public final TableField<ReglementDetailRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.reglement_detail</code> table reference
     */
    public ReglementDetail() {
        this(DSL.name("reglement_detail"), null);
    }

    /**
     * Create an aliased <code>public.reglement_detail</code> table reference
     */
    public ReglementDetail(String alias) {
        this(DSL.name(alias), REGLEMENT_DETAIL);
    }

    /**
     * Create an aliased <code>public.reglement_detail</code> table reference
     */
    public ReglementDetail(Name alias) {
        this(alias, REGLEMENT_DETAIL);
    }

    private ReglementDetail(Name alias, Table<ReglementDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReglementDetail(Name alias, Table<ReglementDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.REGLEMENT_DETAIL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReglementDetailRecord, Long> getIdentity() {
        return Keys.IDENTITY_REGLEMENT_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReglementDetailRecord> getPrimaryKey() {
        return Keys.REGLEMENT_DETAIL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReglementDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<ReglementDetailRecord>>asList(Keys.REGLEMENT_DETAIL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementDetail as(String alias) {
        return new ReglementDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementDetail as(Name alias) {
        return new ReglementDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReglementDetail rename(String name) {
        return new ReglementDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReglementDetail rename(Name name) {
        return new ReglementDetail(name, null);
    }
}
