/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.StructurePartenaireRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StructurePartenaire extends TableImpl<StructurePartenaireRecord> {

    private static final long serialVersionUID = 1886139054;

    /**
     * The reference instance of <code>public.structure_partenaire</code>
     */
    public static final StructurePartenaire STRUCTURE_PARTENAIRE = new StructurePartenaire();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StructurePartenaireRecord> getRecordType() {
        return StructurePartenaireRecord.class;
    }

    /**
     * The column <code>public.structure_partenaire.id</code>.
     */
    public final TableField<StructurePartenaireRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('structure_partenaire_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.structure_partenaire.libelle</code>.
     */
    public final TableField<StructurePartenaireRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.structure_partenaire.who_done</code>.
     */
    public final TableField<StructurePartenaireRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.structure_partenaire.when_done</code>.
     */
    public final TableField<StructurePartenaireRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.structure_partenaire.is_deleted</code>.
     */
    public final TableField<StructurePartenaireRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.structure_partenaire.telephone</code>.
     */
    public final TableField<StructurePartenaireRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.structure_partenaire.region</code>.
     */
    public final TableField<StructurePartenaireRecord, Long> REGION = createField("region", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.structure_partenaire</code> table reference
     */
    public StructurePartenaire() {
        this(DSL.name("structure_partenaire"), null);
    }

    /**
     * Create an aliased <code>public.structure_partenaire</code> table reference
     */
    public StructurePartenaire(String alias) {
        this(DSL.name(alias), STRUCTURE_PARTENAIRE);
    }

    /**
     * Create an aliased <code>public.structure_partenaire</code> table reference
     */
    public StructurePartenaire(Name alias) {
        this(alias, STRUCTURE_PARTENAIRE);
    }

    private StructurePartenaire(Name alias, Table<StructurePartenaireRecord> aliased) {
        this(alias, aliased, null);
    }

    private StructurePartenaire(Name alias, Table<StructurePartenaireRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STRUCTURE_PARTENAIRE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StructurePartenaireRecord, Long> getIdentity() {
        return Keys.IDENTITY_STRUCTURE_PARTENAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StructurePartenaireRecord> getPrimaryKey() {
        return Keys.STRUCTURE_PARTENAIRE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StructurePartenaireRecord>> getKeys() {
        return Arrays.<UniqueKey<StructurePartenaireRecord>>asList(Keys.STRUCTURE_PARTENAIRE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StructurePartenaireRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StructurePartenaireRecord, ?>>asList(Keys.STRUCTURE_PARTENAIRE__FK_REGION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaire as(String alias) {
        return new StructurePartenaire(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StructurePartenaire as(Name alias) {
        return new StructurePartenaire(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StructurePartenaire rename(String name) {
        return new StructurePartenaire(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StructurePartenaire rename(Name name) {
        return new StructurePartenaire(name, null);
    }
}
