/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VAdherentAyantDroitRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentAyantDroit extends TableImpl<VAdherentAyantDroitRecord> {

    private static final long serialVersionUID = -1513990739;

    /**
     * The reference instance of <code>public.v_adherent_ayant_droit</code>
     */
    public static final VAdherentAyantDroit V_ADHERENT_AYANT_DROIT = new VAdherentAyantDroit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VAdherentAyantDroitRecord> getRecordType() {
        return VAdherentAyantDroitRecord.class;
    }

    /**
     * The column <code>public.v_adherent_ayant_droit.id_adherent</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.nom_ad</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.prenom_ad</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.sexe</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.fonction</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> FONCTION = createField("fonction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.date_naiss_adherent</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Timestamp> DATE_NAISS_ADHERENT = createField("date_naiss_adherent", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.date_prise_service</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Timestamp> DATE_PRISE_SERVICE = createField("date_prise_service", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.picture_adherent</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> PICTURE_ADHERENT = createField("picture_adherent", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.direction</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.division</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> DIVISION = createField("division", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.service</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> SERVICE = createField("service", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.telephone</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.matricule</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.structure</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.structure_sigle</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> STRUCTURE_SIGLE = createField("structure_sigle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.code_programme</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> CODE_PROGRAMME = createField("code_programme", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.categorie</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.id_ayant_droit</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> ID_AYANT_DROIT = createField("id_ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.nom_ay</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.date_naiss_ayant_droit</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Timestamp> DATE_NAISS_AYANT_DROIT = createField("date_naiss_ayant_droit", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.age_adherent</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Double> AGE_ADHERENT = createField("age_adherent", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.age</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Double> AGE = createField("age", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.adherent</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, Long> ADHERENT = createField("adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.picture_ayant_droit</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> PICTURE_AYANT_DROIT = createField("picture_ayant_droit", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.lien</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_ayant_droit.genre</code>.
     */
    public final TableField<VAdherentAyantDroitRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_adherent_ayant_droit</code> table reference
     */
    public VAdherentAyantDroit() {
        this(DSL.name("v_adherent_ayant_droit"), null);
    }

    /**
     * Create an aliased <code>public.v_adherent_ayant_droit</code> table reference
     */
    public VAdherentAyantDroit(String alias) {
        this(DSL.name(alias), V_ADHERENT_AYANT_DROIT);
    }

    /**
     * Create an aliased <code>public.v_adherent_ayant_droit</code> table reference
     */
    public VAdherentAyantDroit(Name alias) {
        this(alias, V_ADHERENT_AYANT_DROIT);
    }

    private VAdherentAyantDroit(Name alias, Table<VAdherentAyantDroitRecord> aliased) {
        this(alias, aliased, null);
    }

    private VAdherentAyantDroit(Name alias, Table<VAdherentAyantDroitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentAyantDroit as(String alias) {
        return new VAdherentAyantDroit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentAyantDroit as(Name alias) {
        return new VAdherentAyantDroit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherentAyantDroit rename(String name) {
        return new VAdherentAyantDroit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherentAyantDroit rename(Name name) {
        return new VAdherentAyantDroit(name, null);
    }
}
