/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VAdherentRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherent extends TableImpl<VAdherentRecord> {

    private static final long serialVersionUID = 2129435840;

    /**
     * The reference instance of <code>public.v_adherent</code>
     */
    public static final VAdherent V_ADHERENT = new VAdherent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VAdherentRecord> getRecordType() {
        return VAdherentRecord.class;
    }

    /**
     * The column <code>public.v_adherent.id</code>.
     */
    public final TableField<VAdherentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent.nom_ad</code>.
     */
    public final TableField<VAdherentRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.prenom_ad</code>.
     */
    public final TableField<VAdherentRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.sexe</code>.
     */
    public final TableField<VAdherentRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.matricule</code>.
     */
    public final TableField<VAdherentRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.categorie</code>.
     */
    public final TableField<VAdherentRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_adherent.fonction</code>.
     */
    public final TableField<VAdherentRecord, String> FONCTION = createField("fonction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.structure_sigle</code>.
     */
    public final TableField<VAdherentRecord, String> STRUCTURE_SIGLE = createField("structure_sigle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.date_naiss</code>.
     */
    public final TableField<VAdherentRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent.age</code>.
     */
    public final TableField<VAdherentRecord, Double> AGE = createField("age", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent.date_prise_service</code>.
     */
    public final TableField<VAdherentRecord, Timestamp> DATE_PRISE_SERVICE = createField("date_prise_service", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent.anciennete</code>.
     */
    public final TableField<VAdherentRecord, Double> ANCIENNETE = createField("anciennete", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent.picture</code>.
     */
    public final TableField<VAdherentRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.when_done</code>.
     */
    public final TableField<VAdherentRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent.who_done</code>.
     */
    public final TableField<VAdherentRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.on_deleted</code>.
     */
    public final TableField<VAdherentRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_adherent.direction</code>.
     */
    public final TableField<VAdherentRecord, String> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.division</code>.
     */
    public final TableField<VAdherentRecord, String> DIVISION = createField("division", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.service</code>.
     */
    public final TableField<VAdherentRecord, String> SERVICE = createField("service", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent.telephone</code>.
     */
    public final TableField<VAdherentRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_adherent</code> table reference
     */
    public VAdherent() {
        this(DSL.name("v_adherent"), null);
    }

    /**
     * Create an aliased <code>public.v_adherent</code> table reference
     */
    public VAdherent(String alias) {
        this(DSL.name(alias), V_ADHERENT);
    }

    /**
     * Create an aliased <code>public.v_adherent</code> table reference
     */
    public VAdherent(Name alias) {
        this(alias, V_ADHERENT);
    }

    private VAdherent(Name alias, Table<VAdherentRecord> aliased) {
        this(alias, aliased, null);
    }

    private VAdherent(Name alias, Table<VAdherentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherent as(String alias) {
        return new VAdherent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherent as(Name alias) {
        return new VAdherent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherent rename(String name) {
        return new VAdherent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherent rename(Name name) {
        return new VAdherent(name, null);
    }
}
