/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VDepassementRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDepassement extends TableImpl<VDepassementRecord> {

    private static final long serialVersionUID = 1743700173;

    /**
     * The reference instance of <code>public.v_depassement</code>
     */
    public static final VDepassement V_DEPASSEMENT = new VDepassement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VDepassementRecord> getRecordType() {
        return VDepassementRecord.class;
    }

    /**
     * The column <code>public.v_depassement.matricule</code>.
     */
    public final TableField<VDepassementRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_depassement.nom_ad</code>.
     */
    public final TableField<VDepassementRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_depassement.prenom_ad</code>.
     */
    public final TableField<VDepassementRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_depassement.total_annuel</code>.
     */
    public final TableField<VDepassementRecord, Long> TOTAL_ANNUEL = createField("total_annuel", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_depassement.annee</code>.
     */
    public final TableField<VDepassementRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_depassement</code> table reference
     */
    public VDepassement() {
        this(DSL.name("v_depassement"), null);
    }

    /**
     * Create an aliased <code>public.v_depassement</code> table reference
     */
    public VDepassement(String alias) {
        this(DSL.name(alias), V_DEPASSEMENT);
    }

    /**
     * Create an aliased <code>public.v_depassement</code> table reference
     */
    public VDepassement(Name alias) {
        this(alias, V_DEPASSEMENT);
    }

    private VDepassement(Name alias, Table<VDepassementRecord> aliased) {
        this(alias, aliased, null);
    }

    private VDepassement(Name alias, Table<VDepassementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDepassement as(String alias) {
        return new VDepassement(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDepassement as(Name alias) {
        return new VDepassement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VDepassement rename(String name) {
        return new VDepassement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VDepassement rename(Name name) {
        return new VDepassement(name, null);
    }
}
