/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VEcritureRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VEcriture extends TableImpl<VEcritureRecord> {

    private static final long serialVersionUID = 411720011;

    /**
     * The reference instance of <code>public.v_ecriture</code>
     */
    public static final VEcriture V_ECRITURE = new VEcriture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VEcritureRecord> getRecordType() {
        return VEcritureRecord.class;
    }

    /**
     * The column <code>public.v_ecriture.id_ecriture</code>.
     */
    public final TableField<VEcritureRecord, Long> ID_ECRITURE = createField("id_ecriture", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ecriture.ref_facture</code>.
     */
    public final TableField<VEcritureRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.date_operation</code>.
     */
    public final TableField<VEcritureRecord, Timestamp> DATE_OPERATION = createField("date_operation", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_ecriture.compte</code>.
     */
    public final TableField<VEcritureRecord, Long> COMPTE = createField("compte", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ecriture.num_compte</code>.
     */
    public final TableField<VEcritureRecord, Long> NUM_COMPTE = createField("num_compte", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ecriture.libelle_compte</code>.
     */
    public final TableField<VEcritureRecord, String> LIBELLE_COMPTE = createField("libelle_compte", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.montant</code>.
     */
    public final TableField<VEcritureRecord, Long> MONTANT = createField("montant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ecriture.type_operation</code>.
     */
    public final TableField<VEcritureRecord, String> TYPE_OPERATION = createField("type_operation", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.designation</code>.
     */
    public final TableField<VEcritureRecord, String> DESIGNATION = createField("designation", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.is_deleted</code>.
     */
    public final TableField<VEcritureRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_ecriture.who_done</code>.
     */
    public final TableField<VEcritureRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.when_done</code>.
     */
    public final TableField<VEcritureRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_ecriture.libelle_journal</code>.
     */
    public final TableField<VEcritureRecord, String> LIBELLE_JOURNAL = createField("libelle_journal", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.id_depense</code>.
     */
    public final TableField<VEcritureRecord, Long> ID_DEPENSE = createField("id_depense", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ecriture.ref_depense</code>.
     */
    public final TableField<VEcritureRecord, String> REF_DEPENSE = createField("ref_depense", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ecriture.date_depense</code>.
     */
    public final TableField<VEcritureRecord, Timestamp> DATE_DEPENSE = createField("date_depense", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.v_ecriture</code> table reference
     */
    public VEcriture() {
        this(DSL.name("v_ecriture"), null);
    }

    /**
     * Create an aliased <code>public.v_ecriture</code> table reference
     */
    public VEcriture(String alias) {
        this(DSL.name(alias), V_ECRITURE);
    }

    /**
     * Create an aliased <code>public.v_ecriture</code> table reference
     */
    public VEcriture(Name alias) {
        this(alias, V_ECRITURE);
    }

    private VEcriture(Name alias, Table<VEcritureRecord> aliased) {
        this(alias, aliased, null);
    }

    private VEcriture(Name alias, Table<VEcritureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEcriture as(String alias) {
        return new VEcriture(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEcriture as(Name alias) {
        return new VEcriture(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VEcriture rename(String name) {
        return new VEcriture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VEcriture rename(Name name) {
        return new VEcriture(name, null);
    }
}
