/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VEffectifMainsAyantDroitRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VEffectifMainsAyantDroit extends TableImpl<VEffectifMainsAyantDroitRecord> {

    private static final long serialVersionUID = 1563690305;

    /**
     * The reference instance of <code>public.v_effectif_mains_ayant_droit</code>
     */
    public static final VEffectifMainsAyantDroit V_EFFECTIF_MAINS_AYANT_DROIT = new VEffectifMainsAyantDroit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VEffectifMainsAyantDroitRecord> getRecordType() {
        return VEffectifMainsAyantDroitRecord.class;
    }

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.id</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.nom_ay</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.date_naiss</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.age</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.adherent</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Long> ADHERENT = createField("adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.nom_adherent</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> NOM_ADHERENT = createField("nom_adherent", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.matricule</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.when_done</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.who_done</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.on_deleted</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.picture</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.lien</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains_ayant_droit.genre</code>.
     */
    public final TableField<VEffectifMainsAyantDroitRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_effectif_mains_ayant_droit</code> table reference
     */
    public VEffectifMainsAyantDroit() {
        this(DSL.name("v_effectif_mains_ayant_droit"), null);
    }

    /**
     * Create an aliased <code>public.v_effectif_mains_ayant_droit</code> table reference
     */
    public VEffectifMainsAyantDroit(String alias) {
        this(DSL.name(alias), V_EFFECTIF_MAINS_AYANT_DROIT);
    }

    /**
     * Create an aliased <code>public.v_effectif_mains_ayant_droit</code> table reference
     */
    public VEffectifMainsAyantDroit(Name alias) {
        this(alias, V_EFFECTIF_MAINS_AYANT_DROIT);
    }

    private VEffectifMainsAyantDroit(Name alias, Table<VEffectifMainsAyantDroitRecord> aliased) {
        this(alias, aliased, null);
    }

    private VEffectifMainsAyantDroit(Name alias, Table<VEffectifMainsAyantDroitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEffectifMainsAyantDroit as(String alias) {
        return new VEffectifMainsAyantDroit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEffectifMainsAyantDroit as(Name alias) {
        return new VEffectifMainsAyantDroit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VEffectifMainsAyantDroit rename(String name) {
        return new VEffectifMainsAyantDroit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VEffectifMainsAyantDroit rename(Name name) {
        return new VEffectifMainsAyantDroit(name, null);
    }
}
