/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VEffectifMainsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VEffectifMains extends TableImpl<VEffectifMainsRecord> {

    private static final long serialVersionUID = -764820454;

    /**
     * The reference instance of <code>public.v_effectif_mains</code>
     */
    public static final VEffectifMains V_EFFECTIF_MAINS = new VEffectifMains();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VEffectifMainsRecord> getRecordType() {
        return VEffectifMainsRecord.class;
    }

    /**
     * The column <code>public.v_effectif_mains.id</code>.
     */
    public final TableField<VEffectifMainsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_effectif_mains.nom_ad</code>.
     */
    public final TableField<VEffectifMainsRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.prenom_ad</code>.
     */
    public final TableField<VEffectifMainsRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.sexe</code>.
     */
    public final TableField<VEffectifMainsRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.matricule</code>.
     */
    public final TableField<VEffectifMainsRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.categorie</code>.
     */
    public final TableField<VEffectifMainsRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_effectif_mains.fonction</code>.
     */
    public final TableField<VEffectifMainsRecord, String> FONCTION = createField("fonction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.structure_sigle</code>.
     */
    public final TableField<VEffectifMainsRecord, String> STRUCTURE_SIGLE = createField("structure_sigle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.date_naiss</code>.
     */
    public final TableField<VEffectifMainsRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_effectif_mains.age</code>.
     */
    public final TableField<VEffectifMainsRecord, Double> AGE = createField("age", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_effectif_mains.date_prise_service</code>.
     */
    public final TableField<VEffectifMainsRecord, Timestamp> DATE_PRISE_SERVICE = createField("date_prise_service", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_effectif_mains.anciennete</code>.
     */
    public final TableField<VEffectifMainsRecord, Double> ANCIENNETE = createField("anciennete", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_effectif_mains.picture</code>.
     */
    public final TableField<VEffectifMainsRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.when_done</code>.
     */
    public final TableField<VEffectifMainsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_effectif_mains.who_done</code>.
     */
    public final TableField<VEffectifMainsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.on_deleted</code>.
     */
    public final TableField<VEffectifMainsRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_effectif_mains.direction</code>.
     */
    public final TableField<VEffectifMainsRecord, String> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.division</code>.
     */
    public final TableField<VEffectifMainsRecord, String> DIVISION = createField("division", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.service</code>.
     */
    public final TableField<VEffectifMainsRecord, String> SERVICE = createField("service", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_effectif_mains.telephone</code>.
     */
    public final TableField<VEffectifMainsRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_effectif_mains</code> table reference
     */
    public VEffectifMains() {
        this(DSL.name("v_effectif_mains"), null);
    }

    /**
     * Create an aliased <code>public.v_effectif_mains</code> table reference
     */
    public VEffectifMains(String alias) {
        this(DSL.name(alias), V_EFFECTIF_MAINS);
    }

    /**
     * Create an aliased <code>public.v_effectif_mains</code> table reference
     */
    public VEffectifMains(Name alias) {
        this(alias, V_EFFECTIF_MAINS);
    }

    private VEffectifMains(Name alias, Table<VEffectifMainsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VEffectifMains(Name alias, Table<VEffectifMainsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEffectifMains as(String alias) {
        return new VEffectifMains(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEffectifMains as(Name alias) {
        return new VEffectifMains(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VEffectifMains rename(String name) {
        return new VEffectifMains(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VEffectifMains rename(Name name) {
        return new VEffectifMains(name, null);
    }
}
