/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VNbrBenefiaireParPrestationRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBenefiaireParPrestation extends TableImpl<VNbrBenefiaireParPrestationRecord> {

    private static final long serialVersionUID = -1698683324;

    /**
     * The reference instance of <code>public.v_nbr_benefiaire_par_prestation</code>
     */
    public static final VNbrBenefiaireParPrestation V_NBR_BENEFIAIRE_PAR_PRESTATION = new VNbrBenefiaireParPrestation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VNbrBenefiaireParPrestationRecord> getRecordType() {
        return VNbrBenefiaireParPrestationRecord.class;
    }

    /**
     * The column <code>public.v_nbr_benefiaire_par_prestation.prestation</code>.
     */
    public final TableField<VNbrBenefiaireParPrestationRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_nbr_benefiaire_par_prestation.nbr_adherent_ayant_beneficier</code>.
     */
    public final TableField<VNbrBenefiaireParPrestationRecord, Long> NBR_ADHERENT_AYANT_BENEFICIER = createField("nbr_adherent_ayant_beneficier", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_nbr_benefiaire_par_prestation.nbr_prestation_effectuer</code>.
     */
    public final TableField<VNbrBenefiaireParPrestationRecord, Long> NBR_PRESTATION_EFFECTUER = createField("nbr_prestation_effectuer", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_nbr_benefiaire_par_prestation.annee</code>.
     */
    public final TableField<VNbrBenefiaireParPrestationRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_nbr_benefiaire_par_prestation</code> table reference
     */
    public VNbrBenefiaireParPrestation() {
        this(DSL.name("v_nbr_benefiaire_par_prestation"), null);
    }

    /**
     * Create an aliased <code>public.v_nbr_benefiaire_par_prestation</code> table reference
     */
    public VNbrBenefiaireParPrestation(String alias) {
        this(DSL.name(alias), V_NBR_BENEFIAIRE_PAR_PRESTATION);
    }

    /**
     * Create an aliased <code>public.v_nbr_benefiaire_par_prestation</code> table reference
     */
    public VNbrBenefiaireParPrestation(Name alias) {
        this(alias, V_NBR_BENEFIAIRE_PAR_PRESTATION);
    }

    private VNbrBenefiaireParPrestation(Name alias, Table<VNbrBenefiaireParPrestationRecord> aliased) {
        this(alias, aliased, null);
    }

    private VNbrBenefiaireParPrestation(Name alias, Table<VNbrBenefiaireParPrestationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestation as(String alias) {
        return new VNbrBenefiaireParPrestation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBenefiaireParPrestation as(Name alias) {
        return new VNbrBenefiaireParPrestation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBenefiaireParPrestation rename(String name) {
        return new VNbrBenefiaireParPrestation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBenefiaireParPrestation rename(Name name) {
        return new VNbrBenefiaireParPrestation(name, null);
    }
}
