/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VPartenaireRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPartenaire extends TableImpl<VPartenaireRecord> {

    private static final long serialVersionUID = -1144728627;

    /**
     * The reference instance of <code>public.v_partenaire</code>
     */
    public static final VPartenaire V_PARTENAIRE = new VPartenaire();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPartenaireRecord> getRecordType() {
        return VPartenaireRecord.class;
    }

    /**
     * The column <code>public.v_partenaire.id</code>.
     */
    public final TableField<VPartenaireRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_partenaire.libelle</code>.
     */
    public final TableField<VPartenaireRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_partenaire.who_done</code>.
     */
    public final TableField<VPartenaireRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_partenaire.when_done</code>.
     */
    public final TableField<VPartenaireRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_partenaire.is_deleted</code>.
     */
    public final TableField<VPartenaireRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_partenaire.telephone</code>.
     */
    public final TableField<VPartenaireRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_partenaire.region</code>.
     */
    public final TableField<VPartenaireRecord, String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_partenaire</code> table reference
     */
    public VPartenaire() {
        this(DSL.name("v_partenaire"), null);
    }

    /**
     * Create an aliased <code>public.v_partenaire</code> table reference
     */
    public VPartenaire(String alias) {
        this(DSL.name(alias), V_PARTENAIRE);
    }

    /**
     * Create an aliased <code>public.v_partenaire</code> table reference
     */
    public VPartenaire(Name alias) {
        this(alias, V_PARTENAIRE);
    }

    private VPartenaire(Name alias, Table<VPartenaireRecord> aliased) {
        this(alias, aliased, null);
    }

    private VPartenaire(Name alias, Table<VPartenaireRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPartenaire as(String alias) {
        return new VPartenaire(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPartenaire as(Name alias) {
        return new VPartenaire(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VPartenaire rename(String name) {
        return new VPartenaire(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPartenaire rename(Name name) {
        return new VPartenaire(name, null);
    }
}
