/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VReglementGlobaleRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementGlobale extends TableImpl<VReglementGlobaleRecord> {

    private static final long serialVersionUID = 883708520;

    /**
     * The reference instance of <code>public.v_reglement_globale</code>
     */
    public static final VReglementGlobale V_REGLEMENT_GLOBALE = new VReglementGlobale();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VReglementGlobaleRecord> getRecordType() {
        return VReglementGlobaleRecord.class;
    }

    /**
     * The column <code>public.v_reglement_globale.matricule</code>.
     */
    public final TableField<VReglementGlobaleRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_globale.nom_ad</code>.
     */
    public final TableField<VReglementGlobaleRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_globale.prenom_ad</code>.
     */
    public final TableField<VReglementGlobaleRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_globale.total_annuel</code>.
     */
    public final TableField<VReglementGlobaleRecord, Long> TOTAL_ANNUEL = createField("total_annuel", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_globale.annee</code>.
     */
    public final TableField<VReglementGlobaleRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_reglement_globale</code> table reference
     */
    public VReglementGlobale() {
        this(DSL.name("v_reglement_globale"), null);
    }

    /**
     * Create an aliased <code>public.v_reglement_globale</code> table reference
     */
    public VReglementGlobale(String alias) {
        this(DSL.name(alias), V_REGLEMENT_GLOBALE);
    }

    /**
     * Create an aliased <code>public.v_reglement_globale</code> table reference
     */
    public VReglementGlobale(Name alias) {
        this(alias, V_REGLEMENT_GLOBALE);
    }

    private VReglementGlobale(Name alias, Table<VReglementGlobaleRecord> aliased) {
        this(alias, aliased, null);
    }

    private VReglementGlobale(Name alias, Table<VReglementGlobaleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobale as(String alias) {
        return new VReglementGlobale(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobale as(Name alias) {
        return new VReglementGlobale(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementGlobale rename(String name) {
        return new VReglementGlobale(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementGlobale rename(Name name) {
        return new VReglementGlobale(name, null);
    }
}
