/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VReglementGlobalByAdherentRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementGlobalByAdherent extends TableImpl<VReglementGlobalByAdherentRecord> {

    private static final long serialVersionUID = 333565815;

    /**
     * The reference instance of <code>public.v_reglement_global_by_adherent</code>
     */
    public static final VReglementGlobalByAdherent V_REGLEMENT_GLOBAL_BY_ADHERENT = new VReglementGlobalByAdherent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VReglementGlobalByAdherentRecord> getRecordType() {
        return VReglementGlobalByAdherentRecord.class;
    }

    /**
     * The column <code>public.v_reglement_global_by_adherent.matricule</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_global_by_adherent.nom_ad</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_global_by_adherent.prenom_ad</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_global_by_adherent.total_annuel</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, Long> TOTAL_ANNUEL = createField("total_annuel", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_global_by_adherent.annee</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_global_by_adherent.email</code>.
     */
    public final TableField<VReglementGlobalByAdherentRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_reglement_global_by_adherent</code> table reference
     */
    public VReglementGlobalByAdherent() {
        this(DSL.name("v_reglement_global_by_adherent"), null);
    }

    /**
     * Create an aliased <code>public.v_reglement_global_by_adherent</code> table reference
     */
    public VReglementGlobalByAdherent(String alias) {
        this(DSL.name(alias), V_REGLEMENT_GLOBAL_BY_ADHERENT);
    }

    /**
     * Create an aliased <code>public.v_reglement_global_by_adherent</code> table reference
     */
    public VReglementGlobalByAdherent(Name alias) {
        this(alias, V_REGLEMENT_GLOBAL_BY_ADHERENT);
    }

    private VReglementGlobalByAdherent(Name alias, Table<VReglementGlobalByAdherentRecord> aliased) {
        this(alias, aliased, null);
    }

    private VReglementGlobalByAdherent(Name alias, Table<VReglementGlobalByAdherentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobalByAdherent as(String alias) {
        return new VReglementGlobalByAdherent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementGlobalByAdherent as(Name alias) {
        return new VReglementGlobalByAdherent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementGlobalByAdherent rename(String name) {
        return new VReglementGlobalByAdherent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementGlobalByAdherent rename(Name name) {
        return new VReglementGlobalByAdherent(name, null);
    }
}
