/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VReglement_2Record;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglement_2 extends TableImpl<VReglement_2Record> {

    private static final long serialVersionUID = -1592254555;

    /**
     * The reference instance of <code>public.v_reglement_2</code>
     */
    public static final VReglement_2 V_REGLEMENT_2 = new VReglement_2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VReglement_2Record> getRecordType() {
        return VReglement_2Record.class;
    }

    /**
     * The column <code>public.v_reglement_2.id</code>.
     */
    public final TableField<VReglement_2Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.nom_ad</code>.
     */
    public final TableField<VReglement_2Record, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.prenom_ad</code>.
     */
    public final TableField<VReglement_2Record, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.id_adherent</code>.
     */
    public final TableField<VReglement_2Record, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.matricule</code>.
     */
    public final TableField<VReglement_2Record, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.ref_facture</code>.
     */
    public final TableField<VReglement_2Record, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.structure</code>.
     */
    public final TableField<VReglement_2Record, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.date_payement</code>.
     */
    public final TableField<VReglement_2Record, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_2.who_done</code>.
     */
    public final TableField<VReglement_2Record, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.when_done</code>.
     */
    public final TableField<VReglement_2Record, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_2.annee</code>.
     */
    public final TableField<VReglement_2Record, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.annee_reel</code>.
     */
    public final TableField<VReglement_2Record, String> ANNEE_REEL = createField("annee_reel", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.on_deleted</code>.
     */
    public final TableField<VReglement_2Record, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reglement_2.prestation</code>.
     */
    public final TableField<VReglement_2Record, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reglement_2.couverture</code>.
     */
    public final TableField<VReglement_2Record, String> COUVERTURE = createField("couverture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reglement_2.nom_ay</code>.
     */
    public final TableField<VReglement_2Record, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.lien</code>.
     */
    public final TableField<VReglement_2Record, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.genre</code>.
     */
    public final TableField<VReglement_2Record, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_2.ayant_droit</code>.
     */
    public final TableField<VReglement_2Record, Long> AYANT_DROIT = createField("ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.montant_total</code>.
     */
    public final TableField<VReglement_2Record, Long> MONTANT_TOTAL = createField("montant_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.montant_reglement</code>.
     */
    public final TableField<VReglement_2Record, Long> MONTANT_REGLEMENT = createField("montant_reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.montant_paye</code>.
     */
    public final TableField<VReglement_2Record, Long> MONTANT_PAYE = createField("montant_paye", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_2.id_structure</code>.
     */
    public final TableField<VReglement_2Record, Long> ID_STRUCTURE = createField("id_structure", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_reglement_2</code> table reference
     */
    public VReglement_2() {
        this(DSL.name("v_reglement_2"), null);
    }

    /**
     * Create an aliased <code>public.v_reglement_2</code> table reference
     */
    public VReglement_2(String alias) {
        this(DSL.name(alias), V_REGLEMENT_2);
    }

    /**
     * Create an aliased <code>public.v_reglement_2</code> table reference
     */
    public VReglement_2(Name alias) {
        this(alias, V_REGLEMENT_2);
    }

    private VReglement_2(Name alias, Table<VReglement_2Record> aliased) {
        this(alias, aliased, null);
    }

    private VReglement_2(Name alias, Table<VReglement_2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglement_2 as(String alias) {
        return new VReglement_2(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglement_2 as(Name alias) {
        return new VReglement_2(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglement_2 rename(String name) {
        return new VReglement_2(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglement_2 rename(Name name) {
        return new VReglement_2(name, null);
    }
}
