/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VSituationStructureAdherentRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSituationStructureAdherent extends TableImpl<VSituationStructureAdherentRecord> {

    private static final long serialVersionUID = -515676184;

    /**
     * The reference instance of <code>public.v_situation_structure_adherent</code>
     */
    public static final VSituationStructureAdherent V_SITUATION_STRUCTURE_ADHERENT = new VSituationStructureAdherent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VSituationStructureAdherentRecord> getRecordType() {
        return VSituationStructureAdherentRecord.class;
    }

    /**
     * The column <code>public.v_situation_structure_adherent.matricule</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_situation_structure_adherent.nom_ad</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_situation_structure_adherent.prenom_ad</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_situation_structure_adherent.structure</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_situation_structure_adherent.total_annuel</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, BigDecimal> TOTAL_ANNUEL = createField("total_annuel", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_situation_structure_adherent.annee</code>.
     */
    public final TableField<VSituationStructureAdherentRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_situation_structure_adherent</code> table reference
     */
    public VSituationStructureAdherent() {
        this(DSL.name("v_situation_structure_adherent"), null);
    }

    /**
     * Create an aliased <code>public.v_situation_structure_adherent</code> table reference
     */
    public VSituationStructureAdherent(String alias) {
        this(DSL.name(alias), V_SITUATION_STRUCTURE_ADHERENT);
    }

    /**
     * Create an aliased <code>public.v_situation_structure_adherent</code> table reference
     */
    public VSituationStructureAdherent(Name alias) {
        this(alias, V_SITUATION_STRUCTURE_ADHERENT);
    }

    private VSituationStructureAdherent(Name alias, Table<VSituationStructureAdherentRecord> aliased) {
        this(alias, aliased, null);
    }

    private VSituationStructureAdherent(Name alias, Table<VSituationStructureAdherentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSituationStructureAdherent as(String alias) {
        return new VSituationStructureAdherent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSituationStructureAdherent as(Name alias) {
        return new VSituationStructureAdherent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VSituationStructureAdherent rename(String name) {
        return new VSituationStructureAdherent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VSituationStructureAdherent rename(Name name) {
        return new VSituationStructureAdherent(name, null);
    }
}
