/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VTotalAyantDroitConjointRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTotalAyantDroitConjoint extends TableImpl<VTotalAyantDroitConjointRecord> {

    private static final long serialVersionUID = 1104533971;

    /**
     * The reference instance of <code>public.v_total_ayant_droit_conjoint</code>
     */
    public static final VTotalAyantDroitConjoint V_TOTAL_AYANT_DROIT_CONJOINT = new VTotalAyantDroitConjoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VTotalAyantDroitConjointRecord> getRecordType() {
        return VTotalAyantDroitConjointRecord.class;
    }

    /**
     * The column <code>public.v_total_ayant_droit_conjoint.total_ayant_droit_conjoint</code>.
     */
    public final TableField<VTotalAyantDroitConjointRecord, Long> TOTAL_AYANT_DROIT_CONJOINT = createField("total_ayant_droit_conjoint", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_total_ayant_droit_conjoint.genre</code>.
     */
    public final TableField<VTotalAyantDroitConjointRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_total_ayant_droit_conjoint.lien</code>.
     */
    public final TableField<VTotalAyantDroitConjointRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_total_ayant_droit_conjoint</code> table reference
     */
    public VTotalAyantDroitConjoint() {
        this(DSL.name("v_total_ayant_droit_conjoint"), null);
    }

    /**
     * Create an aliased <code>public.v_total_ayant_droit_conjoint</code> table reference
     */
    public VTotalAyantDroitConjoint(String alias) {
        this(DSL.name(alias), V_TOTAL_AYANT_DROIT_CONJOINT);
    }

    /**
     * Create an aliased <code>public.v_total_ayant_droit_conjoint</code> table reference
     */
    public VTotalAyantDroitConjoint(Name alias) {
        this(alias, V_TOTAL_AYANT_DROIT_CONJOINT);
    }

    private VTotalAyantDroitConjoint(Name alias, Table<VTotalAyantDroitConjointRecord> aliased) {
        this(alias, aliased, null);
    }

    private VTotalAyantDroitConjoint(Name alias, Table<VTotalAyantDroitConjointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTotalAyantDroitConjoint as(String alias) {
        return new VTotalAyantDroitConjoint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTotalAyantDroitConjoint as(Name alias) {
        return new VTotalAyantDroitConjoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VTotalAyantDroitConjoint rename(String name) {
        return new VTotalAyantDroitConjoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VTotalAyantDroitConjoint rename(Name name) {
        return new VTotalAyantDroitConjoint(name, null);
    }
}
