/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VTotalAdherentsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTotalAdherents extends TableImpl<VTotalAdherentsRecord> {

    private static final long serialVersionUID = -1565955942;

    /**
     * The reference instance of <code>public.v_total_adherents</code>
     */
    public static final VTotalAdherents V_TOTAL_ADHERENTS = new VTotalAdherents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VTotalAdherentsRecord> getRecordType() {
        return VTotalAdherentsRecord.class;
    }

    /**
     * The column <code>public.v_total_adherents.total_aherent</code>.
     */
    public final TableField<VTotalAdherentsRecord, Long> TOTAL_AHERENT = createField("total_aherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_total_adherents.sexe</code>.
     */
    public final TableField<VTotalAdherentsRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_total_adherents</code> table reference
     */
    public VTotalAdherents() {
        this(DSL.name("v_total_adherents"), null);
    }

    /**
     * Create an aliased <code>public.v_total_adherents</code> table reference
     */
    public VTotalAdherents(String alias) {
        this(DSL.name(alias), V_TOTAL_ADHERENTS);
    }

    /**
     * Create an aliased <code>public.v_total_adherents</code> table reference
     */
    public VTotalAdherents(Name alias) {
        this(alias, V_TOTAL_ADHERENTS);
    }

    private VTotalAdherents(Name alias, Table<VTotalAdherentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VTotalAdherents(Name alias, Table<VTotalAdherentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTotalAdherents as(String alias) {
        return new VTotalAdherents(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTotalAdherents as(Name alias) {
        return new VTotalAdherents(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VTotalAdherents rename(String name) {
        return new VTotalAdherents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VTotalAdherents rename(Name name) {
        return new VTotalAdherents(name, null);
    }
}
