/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.ZimbraRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Zimbra extends TableImpl<ZimbraRecord> {

    private static final long serialVersionUID = 287497582;

    /**
     * The reference instance of <code>public.zimbra</code>
     */
    public static final Zimbra ZIMBRA = new Zimbra();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZimbraRecord> getRecordType() {
        return ZimbraRecord.class;
    }

    /**
     * The column <code>public.zimbra.id</code>.
     */
    public final TableField<ZimbraRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('zimbra_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.zimbra.telephone</code>.
     */
    public final TableField<ZimbraRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.zimbra.email</code>.
     */
    public final TableField<ZimbraRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.zimbra.mat</code>.
     */
    public final TableField<ZimbraRecord, String> MAT = createField("mat", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.zimbra</code> table reference
     */
    public Zimbra() {
        this(DSL.name("zimbra"), null);
    }

    /**
     * Create an aliased <code>public.zimbra</code> table reference
     */
    public Zimbra(String alias) {
        this(DSL.name(alias), ZIMBRA);
    }

    /**
     * Create an aliased <code>public.zimbra</code> table reference
     */
    public Zimbra(Name alias) {
        this(alias, ZIMBRA);
    }

    private Zimbra(Name alias, Table<ZimbraRecord> aliased) {
        this(alias, aliased, null);
    }

    private Zimbra(Name alias, Table<ZimbraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ZIMBRA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ZimbraRecord, Long> getIdentity() {
        return Keys.IDENTITY_ZIMBRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ZimbraRecord> getPrimaryKey() {
        return Keys.ZIMBRA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ZimbraRecord>> getKeys() {
        return Arrays.<UniqueKey<ZimbraRecord>>asList(Keys.ZIMBRA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Zimbra as(String alias) {
        return new Zimbra(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Zimbra as(Name alias) {
        return new Zimbra(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Zimbra rename(String name) {
        return new Zimbra(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Zimbra rename(Name name) {
        return new Zimbra(name, null);
    }
}
