/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adherent implements Serializable {

    private static final long serialVersionUID = -1336698604;

    private Long      id;
    private String    nomAd;
    private String    prenomAd;
    private String    fonction;
    private Timestamp dateNaiss;
    private Timestamp datePriseService;
    private String    picture;
    private Timestamp whenDone;
    private String    whoDone;
    private Boolean   onDeleted;
    private Long      direction;
    private Long      division;
    private Long      service;
    private String    telephone;
    private String    matricule;
    private String    structure;
    private String    structureSigle;
    private String    codeProgramme;
    private String    categorie;
    private String    sexe;
    private Long      mat;
    private String    email;
    private Boolean   isMember;
    private Boolean   isOkForPrinting;

    public Adherent() {}

    public Adherent(Adherent value) {
        this.id = value.id;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.fonction = value.fonction;
        this.dateNaiss = value.dateNaiss;
        this.datePriseService = value.datePriseService;
        this.picture = value.picture;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.onDeleted = value.onDeleted;
        this.direction = value.direction;
        this.division = value.division;
        this.service = value.service;
        this.telephone = value.telephone;
        this.matricule = value.matricule;
        this.structure = value.structure;
        this.structureSigle = value.structureSigle;
        this.codeProgramme = value.codeProgramme;
        this.categorie = value.categorie;
        this.sexe = value.sexe;
        this.mat = value.mat;
        this.email = value.email;
        this.isMember = value.isMember;
        this.isOkForPrinting = value.isOkForPrinting;
    }

    public Adherent(
        Long      id,
        String    nomAd,
        String    prenomAd,
        String    fonction,
        Timestamp dateNaiss,
        Timestamp datePriseService,
        String    picture,
        Timestamp whenDone,
        String    whoDone,
        Boolean   onDeleted,
        Long      direction,
        Long      division,
        Long      service,
        String    telephone,
        String    matricule,
        String    structure,
        String    structureSigle,
        String    codeProgramme,
        String    categorie,
        String    sexe,
        Long      mat,
        String    email,
        Boolean   isMember,
        Boolean   isOkForPrinting
    ) {
        this.id = id;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.fonction = fonction;
        this.dateNaiss = dateNaiss;
        this.datePriseService = datePriseService;
        this.picture = picture;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.onDeleted = onDeleted;
        this.direction = direction;
        this.division = division;
        this.service = service;
        this.telephone = telephone;
        this.matricule = matricule;
        this.structure = structure;
        this.structureSigle = structureSigle;
        this.codeProgramme = codeProgramme;
        this.categorie = categorie;
        this.sexe = sexe;
        this.mat = mat;
        this.email = email;
        this.isMember = isMember;
        this.isOkForPrinting = isOkForPrinting;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getFonction() {
        return this.fonction;
    }

    public void setFonction(String fonction) {
        this.fonction = fonction;
    }

    public Timestamp getDateNaiss() {
        return this.dateNaiss;
    }

    public void setDateNaiss(Timestamp dateNaiss) {
        this.dateNaiss = dateNaiss;
    }

    public Timestamp getDatePriseService() {
        return this.datePriseService;
    }

    public void setDatePriseService(Timestamp datePriseService) {
        this.datePriseService = datePriseService;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public Long getDirection() {
        return this.direction;
    }

    public void setDirection(Long direction) {
        this.direction = direction;
    }

    public Long getDivision() {
        return this.division;
    }

    public void setDivision(Long division) {
        this.division = division;
    }

    public Long getService() {
        return this.service;
    }

    public void setService(Long service) {
        this.service = service;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public String getStructureSigle() {
        return this.structureSigle;
    }

    public void setStructureSigle(String structureSigle) {
        this.structureSigle = structureSigle;
    }

    public String getCodeProgramme() {
        return this.codeProgramme;
    }

    public void setCodeProgramme(String codeProgramme) {
        this.codeProgramme = codeProgramme;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public Long getMat() {
        return this.mat;
    }

    public void setMat(Long mat) {
        this.mat = mat;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getIsMember() {
        return this.isMember;
    }

    public void setIsMember(Boolean isMember) {
        this.isMember = isMember;
    }

    public Boolean getIsOkForPrinting() {
        return this.isOkForPrinting;
    }

    public void setIsOkForPrinting(Boolean isOkForPrinting) {
        this.isOkForPrinting = isOkForPrinting;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Adherent (");

        sb.append(id);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(fonction);
        sb.append(", ").append(dateNaiss);
        sb.append(", ").append(datePriseService);
        sb.append(", ").append(picture);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(direction);
        sb.append(", ").append(division);
        sb.append(", ").append(service);
        sb.append(", ").append(telephone);
        sb.append(", ").append(matricule);
        sb.append(", ").append(structure);
        sb.append(", ").append(structureSigle);
        sb.append(", ").append(codeProgramme);
        sb.append(", ").append(categorie);
        sb.append(", ").append(sexe);
        sb.append(", ").append(mat);
        sb.append(", ").append(email);
        sb.append(", ").append(isMember);
        sb.append(", ").append(isOkForPrinting);

        sb.append(")");
        return sb.toString();
    }
}
