/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Budget implements Serializable {

    private static final long serialVersionUID = -1550785797;

    private Long      id;
    private Long      gestion;
    private Long      compte;
    private String    typeBuget;
    private Long      montant;
    private Boolean   isDeleted;
    private String    whoDone;
    private Timestamp whenDone;

    public Budget() {}

    public Budget(Budget value) {
        this.id = value.id;
        this.gestion = value.gestion;
        this.compte = value.compte;
        this.typeBuget = value.typeBuget;
        this.montant = value.montant;
        this.isDeleted = value.isDeleted;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
    }

    public Budget(
        Long      id,
        Long      gestion,
        Long      compte,
        String    typeBuget,
        Long      montant,
        Boolean   isDeleted,
        String    whoDone,
        Timestamp whenDone
    ) {
        this.id = id;
        this.gestion = gestion;
        this.compte = compte;
        this.typeBuget = typeBuget;
        this.montant = montant;
        this.isDeleted = isDeleted;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGestion() {
        return this.gestion;
    }

    public void setGestion(Long gestion) {
        this.gestion = gestion;
    }

    public Long getCompte() {
        return this.compte;
    }

    public void setCompte(Long compte) {
        this.compte = compte;
    }

    public String getTypeBuget() {
        return this.typeBuget;
    }

    public void setTypeBuget(String typeBuget) {
        this.typeBuget = typeBuget;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Budget (");

        sb.append(id);
        sb.append(", ").append(gestion);
        sb.append(", ").append(compte);
        sb.append(", ").append(typeBuget);
        sb.append(", ").append(montant);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);

        sb.append(")");
        return sb.toString();
    }
}
