/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategorieCompte implements Serializable {

    private static final long serialVersionUID = -1542052109;

    private Long      id;
    private Long      numCategore;
    private String    libelle;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    whoDone;
    private Boolean   isForBudget;

    public CategorieCompte() {}

    public CategorieCompte(CategorieCompte value) {
        this.id = value.id;
        this.numCategore = value.numCategore;
        this.libelle = value.libelle;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.isForBudget = value.isForBudget;
    }

    public CategorieCompte(
        Long      id,
        Long      numCategore,
        String    libelle,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    whoDone,
        Boolean   isForBudget
    ) {
        this.id = id;
        this.numCategore = numCategore;
        this.libelle = libelle;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.isForBudget = isForBudget;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNumCategore() {
        return this.numCategore;
    }

    public void setNumCategore(Long numCategore) {
        this.numCategore = numCategore;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Boolean getIsForBudget() {
        return this.isForBudget;
    }

    public void setIsForBudget(Boolean isForBudget) {
        this.isForBudget = isForBudget;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategorieCompte (");

        sb.append(id);
        sb.append(", ").append(numCategore);
        sb.append(", ").append(libelle);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(isForBudget);

        sb.append(")");
        return sb.toString();
    }
}
