/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Depense implements Serializable {

    private static final long serialVersionUID = -1801325432;

    private Long      id;
    private String    refDepense;
    private Timestamp dateDepense;
    private Boolean   isDeleted;
    private String    whoDone;
    private Timestamp whenDone;
    private Timestamp lastUpdate;

    public Depense() {}

    public Depense(Depense value) {
        this.id = value.id;
        this.refDepense = value.refDepense;
        this.dateDepense = value.dateDepense;
        this.isDeleted = value.isDeleted;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.lastUpdate = value.lastUpdate;
    }

    public Depense(
        Long      id,
        String    refDepense,
        Timestamp dateDepense,
        Boolean   isDeleted,
        String    whoDone,
        Timestamp whenDone,
        Timestamp lastUpdate
    ) {
        this.id = id;
        this.refDepense = refDepense;
        this.dateDepense = dateDepense;
        this.isDeleted = isDeleted;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.lastUpdate = lastUpdate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRefDepense() {
        return this.refDepense;
    }

    public void setRefDepense(String refDepense) {
        this.refDepense = refDepense;
    }

    public Timestamp getDateDepense() {
        return this.dateDepense;
    }

    public void setDateDepense(Timestamp dateDepense) {
        this.dateDepense = dateDepense;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Depense (");

        sb.append(id);
        sb.append(", ").append(refDepense);
        sb.append(", ").append(dateDepense);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
