/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Params implements Serializable {

    private static final long serialVersionUID = 2092681652;

    private Long    id;
    private String  gestion;
    private Long    plafond;
    private Boolean isDeleted;
    private Long    seuilAlerte;

    public Params() {}

    public Params(Params value) {
        this.id = value.id;
        this.gestion = value.gestion;
        this.plafond = value.plafond;
        this.isDeleted = value.isDeleted;
        this.seuilAlerte = value.seuilAlerte;
    }

    public Params(
        Long    id,
        String  gestion,
        Long    plafond,
        Boolean isDeleted,
        Long    seuilAlerte
    ) {
        this.id = id;
        this.gestion = gestion;
        this.plafond = plafond;
        this.isDeleted = isDeleted;
        this.seuilAlerte = seuilAlerte;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGestion() {
        return this.gestion;
    }

    public void setGestion(String gestion) {
        this.gestion = gestion;
    }

    public Long getPlafond() {
        return this.plafond;
    }

    public void setPlafond(Long plafond) {
        this.plafond = plafond;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Long getSeuilAlerte() {
        return this.seuilAlerte;
    }

    public void setSeuilAlerte(Long seuilAlerte) {
        this.seuilAlerte = seuilAlerte;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Params (");

        sb.append(id);
        sb.append(", ").append(gestion);
        sb.append(", ").append(plafond);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(seuilAlerte);

        sb.append(")");
        return sb.toString();
    }
}
