/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Programme implements Serializable {

    private static final long serialVersionUID = 1462897199;

    private Long      id;
    private String    code;
    private String    libelle;
    private Boolean   onDeleted;
    private String    whoDone;
    private Timestamp whenDone;

    public Programme() {}

    public Programme(Programme value) {
        this.id = value.id;
        this.code = value.code;
        this.libelle = value.libelle;
        this.onDeleted = value.onDeleted;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
    }

    public Programme(
        Long      id,
        String    code,
        String    libelle,
        Boolean   onDeleted,
        String    whoDone,
        Timestamp whenDone
    ) {
        this.id = id;
        this.code = code;
        this.libelle = libelle;
        this.onDeleted = onDeleted;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Programme (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(libelle);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);

        sb.append(")");
        return sb.toString();
    }
}
