/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reglement implements Serializable {

    private static final long serialVersionUID = 1734871667;

    private Long      id;
    private Long      adherent;
    private String    refFacture;
    private Long      structure;
    private Timestamp datePayement;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;
    private Long      typePrestation;
    private Long      ayantDroit;
    private String    structureEmettriceRembourssement;
    private String    telStructureEmettrice;

    public Reglement() {}

    public Reglement(Reglement value) {
        this.id = value.id;
        this.adherent = value.adherent;
        this.refFacture = value.refFacture;
        this.structure = value.structure;
        this.datePayement = value.datePayement;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
        this.typePrestation = value.typePrestation;
        this.ayantDroit = value.ayantDroit;
        this.structureEmettriceRembourssement = value.structureEmettriceRembourssement;
        this.telStructureEmettrice = value.telStructureEmettrice;
    }

    public Reglement(
        Long      id,
        Long      adherent,
        String    refFacture,
        Long      structure,
        Timestamp datePayement,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted,
        Long      typePrestation,
        Long      ayantDroit,
        String    structureEmettriceRembourssement,
        String    telStructureEmettrice
    ) {
        this.id = id;
        this.adherent = adherent;
        this.refFacture = refFacture;
        this.structure = structure;
        this.datePayement = datePayement;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
        this.typePrestation = typePrestation;
        this.ayantDroit = ayantDroit;
        this.structureEmettriceRembourssement = structureEmettriceRembourssement;
        this.telStructureEmettrice = telStructureEmettrice;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdherent() {
        return this.adherent;
    }

    public void setAdherent(Long adherent) {
        this.adherent = adherent;
    }

    public String getRefFacture() {
        return this.refFacture;
    }

    public void setRefFacture(String refFacture) {
        this.refFacture = refFacture;
    }

    public Long getStructure() {
        return this.structure;
    }

    public void setStructure(Long structure) {
        this.structure = structure;
    }

    public Timestamp getDatePayement() {
        return this.datePayement;
    }

    public void setDatePayement(Timestamp datePayement) {
        this.datePayement = datePayement;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public Long getTypePrestation() {
        return this.typePrestation;
    }

    public void setTypePrestation(Long typePrestation) {
        this.typePrestation = typePrestation;
    }

    public Long getAyantDroit() {
        return this.ayantDroit;
    }

    public void setAyantDroit(Long ayantDroit) {
        this.ayantDroit = ayantDroit;
    }

    public String getStructureEmettriceRembourssement() {
        return this.structureEmettriceRembourssement;
    }

    public void setStructureEmettriceRembourssement(String structureEmettriceRembourssement) {
        this.structureEmettriceRembourssement = structureEmettriceRembourssement;
    }

    public String getTelStructureEmettrice() {
        return this.telStructureEmettrice;
    }

    public void setTelStructureEmettrice(String telStructureEmettrice) {
        this.telStructureEmettrice = telStructureEmettrice;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reglement (");

        sb.append(id);
        sb.append(", ").append(adherent);
        sb.append(", ").append(refFacture);
        sb.append(", ").append(structure);
        sb.append(", ").append(datePayement);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(typePrestation);
        sb.append(", ").append(ayantDroit);
        sb.append(", ").append(structureEmettriceRembourssement);
        sb.append(", ").append(telStructureEmettrice);

        sb.append(")");
        return sb.toString();
    }
}
