/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReglementDetail implements Serializable {

    private static final long serialVersionUID = 2081894042;

    private Long      id;
    private Long      reglement;
    private String    intitule;
    private Long      montant;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;
    private Timestamp lastUpdate;

    public ReglementDetail() {}

    public ReglementDetail(ReglementDetail value) {
        this.id = value.id;
        this.reglement = value.reglement;
        this.intitule = value.intitule;
        this.montant = value.montant;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
        this.lastUpdate = value.lastUpdate;
    }

    public ReglementDetail(
        Long      id,
        Long      reglement,
        String    intitule,
        Long      montant,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted,
        Timestamp lastUpdate
    ) {
        this.id = id;
        this.reglement = reglement;
        this.intitule = intitule;
        this.montant = montant;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
        this.lastUpdate = lastUpdate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getReglement() {
        return this.reglement;
    }

    public void setReglement(Long reglement) {
        this.reglement = reglement;
    }

    public String getIntitule() {
        return this.intitule;
    }

    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReglementDetail (");

        sb.append(id);
        sb.append(", ").append(reglement);
        sb.append(", ").append(intitule);
        sb.append(", ").append(montant);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
