/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherent implements Serializable {

    private static final long serialVersionUID = -146281575;

    private Long      id;
    private String    nomAd;
    private String    prenomAd;
    private String    sexe;
    private String    matricule;
    private String    categorie;
    private String    fonction;
    private String    structureSigle;
    private Timestamp dateNaiss;
    private Double    age;
    private Timestamp datePriseService;
    private Double    anciennete;
    private String    picture;
    private Timestamp whenDone;
    private String    whoDone;
    private Boolean   onDeleted;
    private String    direction;
    private String    division;
    private String    service;
    private String    telephone;

    public VAdherent() {}

    public VAdherent(VAdherent value) {
        this.id = value.id;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.sexe = value.sexe;
        this.matricule = value.matricule;
        this.categorie = value.categorie;
        this.fonction = value.fonction;
        this.structureSigle = value.structureSigle;
        this.dateNaiss = value.dateNaiss;
        this.age = value.age;
        this.datePriseService = value.datePriseService;
        this.anciennete = value.anciennete;
        this.picture = value.picture;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.onDeleted = value.onDeleted;
        this.direction = value.direction;
        this.division = value.division;
        this.service = value.service;
        this.telephone = value.telephone;
    }

    public VAdherent(
        Long      id,
        String    nomAd,
        String    prenomAd,
        String    sexe,
        String    matricule,
        String    categorie,
        String    fonction,
        String    structureSigle,
        Timestamp dateNaiss,
        Double    age,
        Timestamp datePriseService,
        Double    anciennete,
        String    picture,
        Timestamp whenDone,
        String    whoDone,
        Boolean   onDeleted,
        String    direction,
        String    division,
        String    service,
        String    telephone
    ) {
        this.id = id;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.sexe = sexe;
        this.matricule = matricule;
        this.categorie = categorie;
        this.fonction = fonction;
        this.structureSigle = structureSigle;
        this.dateNaiss = dateNaiss;
        this.age = age;
        this.datePriseService = datePriseService;
        this.anciennete = anciennete;
        this.picture = picture;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.onDeleted = onDeleted;
        this.direction = direction;
        this.division = division;
        this.service = service;
        this.telephone = telephone;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public String getFonction() {
        return this.fonction;
    }

    public void setFonction(String fonction) {
        this.fonction = fonction;
    }

    public String getStructureSigle() {
        return this.structureSigle;
    }

    public void setStructureSigle(String structureSigle) {
        this.structureSigle = structureSigle;
    }

    public Timestamp getDateNaiss() {
        return this.dateNaiss;
    }

    public void setDateNaiss(Timestamp dateNaiss) {
        this.dateNaiss = dateNaiss;
    }

    public Double getAge() {
        return this.age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    public Timestamp getDatePriseService() {
        return this.datePriseService;
    }

    public void setDatePriseService(Timestamp datePriseService) {
        this.datePriseService = datePriseService;
    }

    public Double getAnciennete() {
        return this.anciennete;
    }

    public void setAnciennete(Double anciennete) {
        this.anciennete = anciennete;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public String getDirection() {
        return this.direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public String getService() {
        return this.service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VAdherent (");

        sb.append(id);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(sexe);
        sb.append(", ").append(matricule);
        sb.append(", ").append(categorie);
        sb.append(", ").append(fonction);
        sb.append(", ").append(structureSigle);
        sb.append(", ").append(dateNaiss);
        sb.append(", ").append(age);
        sb.append(", ").append(datePriseService);
        sb.append(", ").append(anciennete);
        sb.append(", ").append(picture);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(direction);
        sb.append(", ").append(division);
        sb.append(", ").append(service);
        sb.append(", ").append(telephone);

        sb.append(")");
        return sb.toString();
    }
}
