/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentAyantDroit implements Serializable {

    private static final long serialVersionUID = -780570136;

    private Long      idAdherent;
    private String    nomAd;
    private String    prenomAd;
    private String    sexe;
    private String    fonction;
    private Timestamp dateNaissAdherent;
    private Timestamp datePriseService;
    private String    pictureAdherent;
    private Long      direction;
    private Long      division;
    private Long      service;
    private String    telephone;
    private String    matricule;
    private String    structure;
    private String    structureSigle;
    private String    codeProgramme;
    private String    categorie;
    private Long      idAyantDroit;
    private String    nomAy;
    private Timestamp dateNaissAyantDroit;
    private Double    ageAdherent;
    private Double    age;
    private Long      adherent;
    private String    pictureAyantDroit;
    private String    lien;
    private String    genre;

    public VAdherentAyantDroit() {}

    public VAdherentAyantDroit(VAdherentAyantDroit value) {
        this.idAdherent = value.idAdherent;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.sexe = value.sexe;
        this.fonction = value.fonction;
        this.dateNaissAdherent = value.dateNaissAdherent;
        this.datePriseService = value.datePriseService;
        this.pictureAdherent = value.pictureAdherent;
        this.direction = value.direction;
        this.division = value.division;
        this.service = value.service;
        this.telephone = value.telephone;
        this.matricule = value.matricule;
        this.structure = value.structure;
        this.structureSigle = value.structureSigle;
        this.codeProgramme = value.codeProgramme;
        this.categorie = value.categorie;
        this.idAyantDroit = value.idAyantDroit;
        this.nomAy = value.nomAy;
        this.dateNaissAyantDroit = value.dateNaissAyantDroit;
        this.ageAdherent = value.ageAdherent;
        this.age = value.age;
        this.adherent = value.adherent;
        this.pictureAyantDroit = value.pictureAyantDroit;
        this.lien = value.lien;
        this.genre = value.genre;
    }

    public VAdherentAyantDroit(
        Long      idAdherent,
        String    nomAd,
        String    prenomAd,
        String    sexe,
        String    fonction,
        Timestamp dateNaissAdherent,
        Timestamp datePriseService,
        String    pictureAdherent,
        Long      direction,
        Long      division,
        Long      service,
        String    telephone,
        String    matricule,
        String    structure,
        String    structureSigle,
        String    codeProgramme,
        String    categorie,
        Long      idAyantDroit,
        String    nomAy,
        Timestamp dateNaissAyantDroit,
        Double    ageAdherent,
        Double    age,
        Long      adherent,
        String    pictureAyantDroit,
        String    lien,
        String    genre
    ) {
        this.idAdherent = idAdherent;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.sexe = sexe;
        this.fonction = fonction;
        this.dateNaissAdherent = dateNaissAdherent;
        this.datePriseService = datePriseService;
        this.pictureAdherent = pictureAdherent;
        this.direction = direction;
        this.division = division;
        this.service = service;
        this.telephone = telephone;
        this.matricule = matricule;
        this.structure = structure;
        this.structureSigle = structureSigle;
        this.codeProgramme = codeProgramme;
        this.categorie = categorie;
        this.idAyantDroit = idAyantDroit;
        this.nomAy = nomAy;
        this.dateNaissAyantDroit = dateNaissAyantDroit;
        this.ageAdherent = ageAdherent;
        this.age = age;
        this.adherent = adherent;
        this.pictureAyantDroit = pictureAyantDroit;
        this.lien = lien;
        this.genre = genre;
    }

    public Long getIdAdherent() {
        return this.idAdherent;
    }

    public void setIdAdherent(Long idAdherent) {
        this.idAdherent = idAdherent;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public String getFonction() {
        return this.fonction;
    }

    public void setFonction(String fonction) {
        this.fonction = fonction;
    }

    public Timestamp getDateNaissAdherent() {
        return this.dateNaissAdherent;
    }

    public void setDateNaissAdherent(Timestamp dateNaissAdherent) {
        this.dateNaissAdherent = dateNaissAdherent;
    }

    public Timestamp getDatePriseService() {
        return this.datePriseService;
    }

    public void setDatePriseService(Timestamp datePriseService) {
        this.datePriseService = datePriseService;
    }

    public String getPictureAdherent() {
        return this.pictureAdherent;
    }

    public void setPictureAdherent(String pictureAdherent) {
        this.pictureAdherent = pictureAdherent;
    }

    public Long getDirection() {
        return this.direction;
    }

    public void setDirection(Long direction) {
        this.direction = direction;
    }

    public Long getDivision() {
        return this.division;
    }

    public void setDivision(Long division) {
        this.division = division;
    }

    public Long getService() {
        return this.service;
    }

    public void setService(Long service) {
        this.service = service;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public String getStructureSigle() {
        return this.structureSigle;
    }

    public void setStructureSigle(String structureSigle) {
        this.structureSigle = structureSigle;
    }

    public String getCodeProgramme() {
        return this.codeProgramme;
    }

    public void setCodeProgramme(String codeProgramme) {
        this.codeProgramme = codeProgramme;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public Long getIdAyantDroit() {
        return this.idAyantDroit;
    }

    public void setIdAyantDroit(Long idAyantDroit) {
        this.idAyantDroit = idAyantDroit;
    }

    public String getNomAy() {
        return this.nomAy;
    }

    public void setNomAy(String nomAy) {
        this.nomAy = nomAy;
    }

    public Timestamp getDateNaissAyantDroit() {
        return this.dateNaissAyantDroit;
    }

    public void setDateNaissAyantDroit(Timestamp dateNaissAyantDroit) {
        this.dateNaissAyantDroit = dateNaissAyantDroit;
    }

    public Double getAgeAdherent() {
        return this.ageAdherent;
    }

    public void setAgeAdherent(Double ageAdherent) {
        this.ageAdherent = ageAdherent;
    }

    public Double getAge() {
        return this.age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    public Long getAdherent() {
        return this.adherent;
    }

    public void setAdherent(Long adherent) {
        this.adherent = adherent;
    }

    public String getPictureAyantDroit() {
        return this.pictureAyantDroit;
    }

    public void setPictureAyantDroit(String pictureAyantDroit) {
        this.pictureAyantDroit = pictureAyantDroit;
    }

    public String getLien() {
        return this.lien;
    }

    public void setLien(String lien) {
        this.lien = lien;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VAdherentAyantDroit (");

        sb.append(idAdherent);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(sexe);
        sb.append(", ").append(fonction);
        sb.append(", ").append(dateNaissAdherent);
        sb.append(", ").append(datePriseService);
        sb.append(", ").append(pictureAdherent);
        sb.append(", ").append(direction);
        sb.append(", ").append(division);
        sb.append(", ").append(service);
        sb.append(", ").append(telephone);
        sb.append(", ").append(matricule);
        sb.append(", ").append(structure);
        sb.append(", ").append(structureSigle);
        sb.append(", ").append(codeProgramme);
        sb.append(", ").append(categorie);
        sb.append(", ").append(idAyantDroit);
        sb.append(", ").append(nomAy);
        sb.append(", ").append(dateNaissAyantDroit);
        sb.append(", ").append(ageAdherent);
        sb.append(", ").append(age);
        sb.append(", ").append(adherent);
        sb.append(", ").append(pictureAyantDroit);
        sb.append(", ").append(lien);
        sb.append(", ").append(genre);

        sb.append(")");
        return sb.toString();
    }
}
