/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCumuleByStructure implements Serializable {

    private static final long serialVersionUID = -1741329462;

    private String     structure;
    private BigDecimal totalAnnuel;
    private String     annee;

    public VCumuleByStructure() {}

    public VCumuleByStructure(VCumuleByStructure value) {
        this.structure = value.structure;
        this.totalAnnuel = value.totalAnnuel;
        this.annee = value.annee;
    }

    public VCumuleByStructure(
        String     structure,
        BigDecimal totalAnnuel,
        String     annee
    ) {
        this.structure = structure;
        this.totalAnnuel = totalAnnuel;
        this.annee = annee;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public BigDecimal getTotalAnnuel() {
        return this.totalAnnuel;
    }

    public void setTotalAnnuel(BigDecimal totalAnnuel) {
        this.totalAnnuel = totalAnnuel;
    }

    public String getAnnee() {
        return this.annee;
    }

    public void setAnnee(String annee) {
        this.annee = annee;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VCumuleByStructure (");

        sb.append(structure);
        sb.append(", ").append(totalAnnuel);
        sb.append(", ").append(annee);

        sb.append(")");
        return sb.toString();
    }
}
