/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrPrestationParAdherent implements Serializable {

    private static final long serialVersionUID = 595539991;

    private String matricule;
    private String nomAd;
    private String prenomAd;
    private String prestation;
    private Long   nombrePrestation;
    private String annee;

    public VNbrPrestationParAdherent() {}

    public VNbrPrestationParAdherent(VNbrPrestationParAdherent value) {
        this.matricule = value.matricule;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.prestation = value.prestation;
        this.nombrePrestation = value.nombrePrestation;
        this.annee = value.annee;
    }

    public VNbrPrestationParAdherent(
        String matricule,
        String nomAd,
        String prenomAd,
        String prestation,
        Long   nombrePrestation,
        String annee
    ) {
        this.matricule = matricule;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.prestation = prestation;
        this.nombrePrestation = nombrePrestation;
        this.annee = annee;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getPrestation() {
        return this.prestation;
    }

    public void setPrestation(String prestation) {
        this.prestation = prestation;
    }

    public Long getNombrePrestation() {
        return this.nombrePrestation;
    }

    public void setNombrePrestation(Long nombrePrestation) {
        this.nombrePrestation = nombrePrestation;
    }

    public String getAnnee() {
        return this.annee;
    }

    public void setAnnee(String annee) {
        this.annee = annee;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VNbrPrestationParAdherent (");

        sb.append(matricule);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(prestation);
        sb.append(", ").append(nombrePrestation);
        sb.append(", ").append(annee);

        sb.append(")");
        return sb.toString();
    }
}
