/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSituationStructureAdherent implements Serializable {

    private static final long serialVersionUID = -832547011;

    private String     matricule;
    private String     nomAd;
    private String     prenomAd;
    private String     structure;
    private BigDecimal totalAnnuel;
    private String     annee;

    public VSituationStructureAdherent() {}

    public VSituationStructureAdherent(VSituationStructureAdherent value) {
        this.matricule = value.matricule;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.structure = value.structure;
        this.totalAnnuel = value.totalAnnuel;
        this.annee = value.annee;
    }

    public VSituationStructureAdherent(
        String     matricule,
        String     nomAd,
        String     prenomAd,
        String     structure,
        BigDecimal totalAnnuel,
        String     annee
    ) {
        this.matricule = matricule;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.structure = structure;
        this.totalAnnuel = totalAnnuel;
        this.annee = annee;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public BigDecimal getTotalAnnuel() {
        return this.totalAnnuel;
    }

    public void setTotalAnnuel(BigDecimal totalAnnuel) {
        this.totalAnnuel = totalAnnuel;
    }

    public String getAnnee() {
        return this.annee;
    }

    public void setAnnee(String annee) {
        this.annee = annee;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VSituationStructureAdherent (");

        sb.append(matricule);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(structure);
        sb.append(", ").append(totalAnnuel);
        sb.append(", ").append(annee);

        sb.append(")");
        return sb.toString();
    }
}
