/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTotalAdherents implements Serializable {

    private static final long serialVersionUID = 1089116768;

    private Long   totalAherent;
    private String sexe;

    public VTotalAdherents() {}

    public VTotalAdherents(VTotalAdherents value) {
        this.totalAherent = value.totalAherent;
        this.sexe = value.sexe;
    }

    public VTotalAdherents(
        Long   totalAherent,
        String sexe
    ) {
        this.totalAherent = totalAherent;
        this.sexe = sexe;
    }

    public Long getTotalAherent() {
        return this.totalAherent;
    }

    public void setTotalAherent(Long totalAherent) {
        this.totalAherent = totalAherent;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VTotalAdherents (");

        sb.append(totalAherent);
        sb.append(", ").append(sexe);

        sb.append(")");
        return sb.toString();
    }
}
