/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTotalAyantDroitEnfant implements Serializable {

    private static final long serialVersionUID = 365629978;

    private Long   totalAyantDroitEnfant;
    private String genre;
    private String lien;

    public VTotalAyantDroitEnfant() {}

    public VTotalAyantDroitEnfant(VTotalAyantDroitEnfant value) {
        this.totalAyantDroitEnfant = value.totalAyantDroitEnfant;
        this.genre = value.genre;
        this.lien = value.lien;
    }

    public VTotalAyantDroitEnfant(
        Long   totalAyantDroitEnfant,
        String genre,
        String lien
    ) {
        this.totalAyantDroitEnfant = totalAyantDroitEnfant;
        this.genre = genre;
        this.lien = lien;
    }

    public Long getTotalAyantDroitEnfant() {
        return this.totalAyantDroitEnfant;
    }

    public void setTotalAyantDroitEnfant(Long totalAyantDroitEnfant) {
        this.totalAyantDroitEnfant = totalAyantDroitEnfant;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getLien() {
        return this.lien;
    }

    public void setLien(String lien) {
        this.lien = lien;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VTotalAyantDroitEnfant (");

        sb.append(totalAyantDroitEnfant);
        sb.append(", ").append(genre);
        sb.append(", ").append(lien);

        sb.append(")");
        return sb.toString();
    }
}
