/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import models.tables.Adherent;
import models.tables.AyantDroit;
import models.tables.Budget;
import models.tables.Categorie;
import models.tables.CategorieCompte;
import models.tables.ClassCompte;
import models.tables.Connexion;
import models.tables.Depense;
import models.tables.Direction;
import models.tables.Division;
import models.tables.Ecriture;
import models.tables.Email;
import models.tables.JournalEcriture;
import models.tables.Params;
import models.tables.Programme;
import models.tables.Region;
import models.tables.Reglement;
import models.tables.ReglementDetail;
import models.tables.Service;
import models.tables.StructurePartenaire;
import models.tables.TypePrestation;
import models.tables.Users;
import models.tables.Zimbra;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADHERENT_PKEY = Indexes0.ADHERENT_PKEY;
    public static final Index AYANT_DROIT_PKEY = Indexes0.AYANT_DROIT_PKEY;
    public static final Index BUDGET_PKEY = Indexes0.BUDGET_PKEY;
    public static final Index UNIK_BUGET_ROW = Indexes0.UNIK_BUGET_ROW;
    public static final Index CATEGORIE_PKEY = Indexes0.CATEGORIE_PKEY;
    public static final Index CODE = Indexes0.CODE;
    public static final Index CAT_UNIK_KEY = Indexes0.CAT_UNIK_KEY;
    public static final Index CATEGORIE_COMPTE_PKEY = Indexes0.CATEGORIE_COMPTE_PKEY;
    public static final Index CLASS_COMPTE_PKEY = Indexes0.CLASS_COMPTE_PKEY;
    public static final Index NUM_COMPTE_UNIK = Indexes0.NUM_COMPTE_UNIK;
    public static final Index CONNEXION_PKEY = Indexes0.CONNEXION_PKEY;
    public static final Index PRIMARY_DEPENSE = Indexes0.PRIMARY_DEPENSE;
    public static final Index DIRECTION_PKEY = Indexes0.DIRECTION_PKEY;
    public static final Index DIVISION_PKEY = Indexes0.DIVISION_PKEY;
    public static final Index ECRITURE_PKEY = Indexes0.ECRITURE_PKEY;
    public static final Index EMAIL_PKEY = Indexes0.EMAIL_PKEY;
    public static final Index JOURNAL_ECRITURE_PKEY = Indexes0.JOURNAL_ECRITURE_PKEY;
    public static final Index UNIK_JOURNAL_KEY = Indexes0.UNIK_JOURNAL_KEY;
    public static final Index PARAMS_PKEY = Indexes0.PARAMS_PKEY;
    public static final Index CODE_PRGM = Indexes0.CODE_PRGM;
    public static final Index PROGRAMME_PKEY = Indexes0.PROGRAMME_PKEY;
    public static final Index REGION_PKEY = Indexes0.REGION_PKEY;
    public static final Index REGLEMENT_PKEY = Indexes0.REGLEMENT_PKEY;
    public static final Index REGLEMENT_DETAIL_PKEY = Indexes0.REGLEMENT_DETAIL_PKEY;
    public static final Index SERVICE_PKEY = Indexes0.SERVICE_PKEY;
    public static final Index STRUCTURE_PARTENAIRE_PKEY = Indexes0.STRUCTURE_PARTENAIRE_PKEY;
    public static final Index TYPE_PRESTATION_PKEY = Indexes0.TYPE_PRESTATION_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index ZIMBRA_PKEY = Indexes0.ZIMBRA_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ADHERENT_PKEY = createIndex("adherent_pkey", Adherent.ADHERENT, new OrderField[] { Adherent.ADHERENT.ID }, true);
        public static Index AYANT_DROIT_PKEY = createIndex("ayant_droit_pkey", AyantDroit.AYANT_DROIT, new OrderField[] { AyantDroit.AYANT_DROIT.ID }, true);
        public static Index BUDGET_PKEY = createIndex("budget_pkey", Budget.BUDGET, new OrderField[] { Budget.BUDGET.ID }, true);
        public static Index UNIK_BUGET_ROW = createIndex("unik_buget_row", Budget.BUDGET, new OrderField[] { Budget.BUDGET.GESTION, Budget.BUDGET.COMPTE, Budget.BUDGET.TYPE_BUGET }, true);
        public static Index CATEGORIE_PKEY = createIndex("categorie_pkey", Categorie.CATEGORIE, new OrderField[] { Categorie.CATEGORIE.ID }, true);
        public static Index CODE = createIndex("code", Categorie.CATEGORIE, new OrderField[] { Categorie.CATEGORIE.CODE }, true);
        public static Index CAT_UNIK_KEY = createIndex("cat_unik_key", CategorieCompte.CATEGORIE_COMPTE, new OrderField[] { CategorieCompte.CATEGORIE_COMPTE.NUM_CATEGORE }, true);
        public static Index CATEGORIE_COMPTE_PKEY = createIndex("categorie_compte_pkey", CategorieCompte.CATEGORIE_COMPTE, new OrderField[] { CategorieCompte.CATEGORIE_COMPTE.ID }, true);
        public static Index CLASS_COMPTE_PKEY = createIndex("class_compte_pkey", ClassCompte.CLASS_COMPTE, new OrderField[] { ClassCompte.CLASS_COMPTE.ID }, true);
        public static Index NUM_COMPTE_UNIK = createIndex("num_compte_unik", ClassCompte.CLASS_COMPTE, new OrderField[] { ClassCompte.CLASS_COMPTE.NUM_COMPTE }, true);
        public static Index CONNEXION_PKEY = createIndex("connexion_pkey", Connexion.CONNEXION, new OrderField[] { Connexion.CONNEXION.ID }, true);
        public static Index PRIMARY_DEPENSE = createIndex("primary_depense", Depense.DEPENSE, new OrderField[] { Depense.DEPENSE.ID }, true);
        public static Index DIRECTION_PKEY = createIndex("Direction_pkey", Direction.DIRECTION, new OrderField[] { Direction.DIRECTION.ID }, true);
        public static Index DIVISION_PKEY = createIndex("division_pkey", Division.DIVISION, new OrderField[] { Division.DIVISION.ID }, true);
        public static Index ECRITURE_PKEY = createIndex("ecriture_pkey", Ecriture.ECRITURE, new OrderField[] { Ecriture.ECRITURE.ID }, true);
        public static Index EMAIL_PKEY = createIndex("email_pkey", Email.EMAIL, new OrderField[] { Email.EMAIL.ID }, true);
        public static Index JOURNAL_ECRITURE_PKEY = createIndex("journal_ecriture_pkey", JournalEcriture.JOURNAL_ECRITURE, new OrderField[] { JournalEcriture.JOURNAL_ECRITURE.ID }, true);
        public static Index UNIK_JOURNAL_KEY = createIndex("unik_journal_key", JournalEcriture.JOURNAL_ECRITURE, new OrderField[] { JournalEcriture.JOURNAL_ECRITURE.NUM_JOURNAL }, true);
        public static Index PARAMS_PKEY = createIndex("params_pkey", Params.PARAMS, new OrderField[] { Params.PARAMS.ID }, true);
        public static Index CODE_PRGM = createIndex("code_prgm", Programme.PROGRAMME, new OrderField[] { Programme.PROGRAMME.CODE }, true);
        public static Index PROGRAMME_PKEY = createIndex("programme_pkey", Programme.PROGRAMME, new OrderField[] { Programme.PROGRAMME.ID }, true);
        public static Index REGION_PKEY = createIndex("region_pkey", Region.REGION, new OrderField[] { Region.REGION.ID }, true);
        public static Index REGLEMENT_PKEY = createIndex("reglement_pkey", Reglement.REGLEMENT, new OrderField[] { Reglement.REGLEMENT.ID }, true);
        public static Index REGLEMENT_DETAIL_PKEY = createIndex("reglement_detail_pkey", ReglementDetail.REGLEMENT_DETAIL, new OrderField[] { ReglementDetail.REGLEMENT_DETAIL.ID }, true);
        public static Index SERVICE_PKEY = createIndex("service_pkey", Service.SERVICE, new OrderField[] { Service.SERVICE.ID }, true);
        public static Index STRUCTURE_PARTENAIRE_PKEY = createIndex("structure_partenaire_pkey", StructurePartenaire.STRUCTURE_PARTENAIRE, new OrderField[] { StructurePartenaire.STRUCTURE_PARTENAIRE.ID }, true);
        public static Index TYPE_PRESTATION_PKEY = createIndex("type_prestation_pkey", TypePrestation.TYPE_PRESTATION, new OrderField[] { TypePrestation.TYPE_PRESTATION.ID }, true);
        public static Index USERS_PKEY = createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
        public static Index ZIMBRA_PKEY = createIndex("zimbra_pkey", Zimbra.ZIMBRA, new OrderField[] { Zimbra.ZIMBRA.ID }, true);
    }
}
