/*
 * This file is generated by jOOQ.
*/
package models;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Adherent;
import models.tables.AdherentTmp;
import models.tables.AyantDroit;
import models.tables.Budget;
import models.tables.Categorie;
import models.tables.CategorieCompte;
import models.tables.ClassCompte;
import models.tables.Connexion;
import models.tables.Depense;
import models.tables.Direction;
import models.tables.Division;
import models.tables.Ecriture;
import models.tables.Email;
import models.tables.JournalEcriture;
import models.tables.Params;
import models.tables.Personnel;
import models.tables.Programme;
import models.tables.Region;
import models.tables.Reglement;
import models.tables.ReglementDetail;
import models.tables.Service;
import models.tables.StructurePartenaire;
import models.tables.TypePrestation;
import models.tables.Users;
import models.tables.VAdherent;
import models.tables.VAdherentAyantDroit;
import models.tables.VAyantDroit;
import models.tables.VBudget;
import models.tables.VCumuleByStructure;
import models.tables.VCumuleByStructureTypePrestation;
import models.tables.VCumuleByTypePrestation;
import models.tables.VDepassement;
import models.tables.VEcriture;
import models.tables.VEffectifMains;
import models.tables.VEffectifMainsAyantDroit;
import models.tables.VNbrBenefiaireParPrestation;
import models.tables.VNbrPrestationParAdherent;
import models.tables.VPartenaire;
import models.tables.VReglement;
import models.tables.VReglementGlobal;
import models.tables.VReglementGlobalByAdherent;
import models.tables.VReglementGlobalParType;
import models.tables.VReglementGlobale;
import models.tables.VReglement_2;
import models.tables.VSituationStructureAdherent;
import models.tables.VSituationStructurePrestationAdherent;
import models.tables.VTotalAdherents;
import models.tables.VTotalAyantDroitConjoint;
import models.tables.VTotalAyantDroitEnfant;
import models.tables.Zimbra;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1346947191;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.adherent</code>.
     */
    public final Adherent ADHERENT = models.tables.Adherent.ADHERENT;

    /**
     * The table <code>public.adherent_tmp</code>.
     */
    public final AdherentTmp ADHERENT_TMP = models.tables.AdherentTmp.ADHERENT_TMP;

    /**
     * The table <code>public.ayant_droit</code>.
     */
    public final AyantDroit AYANT_DROIT = models.tables.AyantDroit.AYANT_DROIT;

    /**
     * The table <code>public.budget</code>.
     */
    public final Budget BUDGET = models.tables.Budget.BUDGET;

    /**
     * The table <code>public.categorie</code>.
     */
    public final Categorie CATEGORIE = models.tables.Categorie.CATEGORIE;

    /**
     * The table <code>public.categorie_compte</code>.
     */
    public final CategorieCompte CATEGORIE_COMPTE = models.tables.CategorieCompte.CATEGORIE_COMPTE;

    /**
     * The table <code>public.class_compte</code>.
     */
    public final ClassCompte CLASS_COMPTE = models.tables.ClassCompte.CLASS_COMPTE;

    /**
     * The table <code>public.connexion</code>.
     */
    public final Connexion CONNEXION = models.tables.Connexion.CONNEXION;

    /**
     * The table <code>public.depense</code>.
     */
    public final Depense DEPENSE = models.tables.Depense.DEPENSE;

    /**
     * The table <code>public.direction</code>.
     */
    public final Direction DIRECTION = models.tables.Direction.DIRECTION;

    /**
     * The table <code>public.division</code>.
     */
    public final Division DIVISION = models.tables.Division.DIVISION;

    /**
     * The table <code>public.ecriture</code>.
     */
    public final Ecriture ECRITURE = models.tables.Ecriture.ECRITURE;

    /**
     * The table <code>public.email</code>.
     */
    public final Email EMAIL = models.tables.Email.EMAIL;

    /**
     * The table <code>public.journal_ecriture</code>.
     */
    public final JournalEcriture JOURNAL_ECRITURE = models.tables.JournalEcriture.JOURNAL_ECRITURE;

    /**
     * The table <code>public.params</code>.
     */
    public final Params PARAMS = models.tables.Params.PARAMS;

    /**
     * The table <code>public.personnel</code>.
     */
    public final Personnel PERSONNEL = models.tables.Personnel.PERSONNEL;

    /**
     * The table <code>public.programme</code>.
     */
    public final Programme PROGRAMME = models.tables.Programme.PROGRAMME;

    /**
     * The table <code>public.region</code>.
     */
    public final Region REGION = models.tables.Region.REGION;

    /**
     * The table <code>public.reglement</code>.
     */
    public final Reglement REGLEMENT = models.tables.Reglement.REGLEMENT;

    /**
     * The table <code>public.reglement_detail</code>.
     */
    public final ReglementDetail REGLEMENT_DETAIL = models.tables.ReglementDetail.REGLEMENT_DETAIL;

    /**
     * The table <code>public.service</code>.
     */
    public final Service SERVICE = models.tables.Service.SERVICE;

    /**
     * The table <code>public.structure_partenaire</code>.
     */
    public final StructurePartenaire STRUCTURE_PARTENAIRE = models.tables.StructurePartenaire.STRUCTURE_PARTENAIRE;

    /**
     * The table <code>public.type_prestation</code>.
     */
    public final TypePrestation TYPE_PRESTATION = models.tables.TypePrestation.TYPE_PRESTATION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = models.tables.Users.USERS;

    /**
     * The table <code>public.v_adherent</code>.
     */
    public final VAdherent V_ADHERENT = models.tables.VAdherent.V_ADHERENT;

    /**
     * The table <code>public.v_adherent_ayant_droit</code>.
     */
    public final VAdherentAyantDroit V_ADHERENT_AYANT_DROIT = models.tables.VAdherentAyantDroit.V_ADHERENT_AYANT_DROIT;

    /**
     * The table <code>public.v_ayant_droit</code>.
     */
    public final VAyantDroit V_AYANT_DROIT = models.tables.VAyantDroit.V_AYANT_DROIT;

    /**
     * The table <code>public.v_budget</code>.
     */
    public final VBudget V_BUDGET = models.tables.VBudget.V_BUDGET;

    /**
     * The table <code>public.v_cumule_by_structure</code>.
     */
    public final VCumuleByStructure V_CUMULE_BY_STRUCTURE = models.tables.VCumuleByStructure.V_CUMULE_BY_STRUCTURE;

    /**
     * The table <code>public.v_cumule_by_structure_type_prestation</code>.
     */
    public final VCumuleByStructureTypePrestation V_CUMULE_BY_STRUCTURE_TYPE_PRESTATION = models.tables.VCumuleByStructureTypePrestation.V_CUMULE_BY_STRUCTURE_TYPE_PRESTATION;

    /**
     * The table <code>public.v_cumule_by_type_prestation</code>.
     */
    public final VCumuleByTypePrestation V_CUMULE_BY_TYPE_PRESTATION = models.tables.VCumuleByTypePrestation.V_CUMULE_BY_TYPE_PRESTATION;

    /**
     * The table <code>public.v_depassement</code>.
     */
    public final VDepassement V_DEPASSEMENT = models.tables.VDepassement.V_DEPASSEMENT;

    /**
     * The table <code>public.v_ecriture</code>.
     */
    public final VEcriture V_ECRITURE = models.tables.VEcriture.V_ECRITURE;

    /**
     * The table <code>public.v_effectif_mains</code>.
     */
    public final VEffectifMains V_EFFECTIF_MAINS = models.tables.VEffectifMains.V_EFFECTIF_MAINS;

    /**
     * The table <code>public.v_effectif_mains_ayant_droit</code>.
     */
    public final VEffectifMainsAyantDroit V_EFFECTIF_MAINS_AYANT_DROIT = models.tables.VEffectifMainsAyantDroit.V_EFFECTIF_MAINS_AYANT_DROIT;

    /**
     * The table <code>public.v_nbr_benefiaire_par_prestation</code>.
     */
    public final VNbrBenefiaireParPrestation V_NBR_BENEFIAIRE_PAR_PRESTATION = models.tables.VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION;

    /**
     * The table <code>public.v_nbr_prestation_par_adherent</code>.
     */
    public final VNbrPrestationParAdherent V_NBR_PRESTATION_PAR_ADHERENT = models.tables.VNbrPrestationParAdherent.V_NBR_PRESTATION_PAR_ADHERENT;

    /**
     * The table <code>public.v_partenaire</code>.
     */
    public final VPartenaire V_PARTENAIRE = models.tables.VPartenaire.V_PARTENAIRE;

    /**
     * The table <code>public.v_reglement</code>.
     */
    public final VReglement V_REGLEMENT = models.tables.VReglement.V_REGLEMENT;

    /**
     * The table <code>public.v_reglement_2</code>.
     */
    public final VReglement_2 V_REGLEMENT_2 = models.tables.VReglement_2.V_REGLEMENT_2;

    /**
     * The table <code>public.v_reglement_global</code>.
     */
    public final VReglementGlobal V_REGLEMENT_GLOBAL = models.tables.VReglementGlobal.V_REGLEMENT_GLOBAL;

    /**
     * The table <code>public.v_reglement_global_by_adherent</code>.
     */
    public final VReglementGlobalByAdherent V_REGLEMENT_GLOBAL_BY_ADHERENT = models.tables.VReglementGlobalByAdherent.V_REGLEMENT_GLOBAL_BY_ADHERENT;

    /**
     * The table <code>public.v_reglement_global_par_type</code>.
     */
    public final VReglementGlobalParType V_REGLEMENT_GLOBAL_PAR_TYPE = models.tables.VReglementGlobalParType.V_REGLEMENT_GLOBAL_PAR_TYPE;

    /**
     * The table <code>public.v_reglement_globale</code>.
     */
    public final VReglementGlobale V_REGLEMENT_GLOBALE = models.tables.VReglementGlobale.V_REGLEMENT_GLOBALE;

    /**
     * The table <code>public.v_situation_structure_adherent</code>.
     */
    public final VSituationStructureAdherent V_SITUATION_STRUCTURE_ADHERENT = models.tables.VSituationStructureAdherent.V_SITUATION_STRUCTURE_ADHERENT;

    /**
     * The table <code>public.v_situation_structure_prestation_adherent</code>.
     */
    public final VSituationStructurePrestationAdherent V_SITUATION_STRUCTURE_PRESTATION_ADHERENT = models.tables.VSituationStructurePrestationAdherent.V_SITUATION_STRUCTURE_PRESTATION_ADHERENT;

    /**
     * The table <code>public.v_total_adherents</code>.
     */
    public final VTotalAdherents V_TOTAL_ADHERENTS = models.tables.VTotalAdherents.V_TOTAL_ADHERENTS;

    /**
     * The table <code>public.v_total_ayant_droit_conjoint</code>.
     */
    public final VTotalAyantDroitConjoint V_TOTAL_AYANT_DROIT_CONJOINT = models.tables.VTotalAyantDroitConjoint.V_TOTAL_AYANT_DROIT_CONJOINT;

    /**
     * The table <code>public.v_total_ayant_droit_enfant</code>.
     */
    public final VTotalAyantDroitEnfant V_TOTAL_AYANT_DROIT_ENFANT = models.tables.VTotalAyantDroitEnfant.V_TOTAL_AYANT_DROIT_ENFANT;

    /**
     * The table <code>public.zimbra</code>.
     */
    public final Zimbra ZIMBRA = models.tables.Zimbra.ZIMBRA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADHERENT_ID_SEQ,
            Sequences.ADHERENT_TMP_ID_SEQ,
            Sequences.AYANT_DROIT_ID_SEQ,
            Sequences.BUDGET_ID_SEQ,
            Sequences.CATEGORIE_COMPTE_ID_SEQ,
            Sequences.CATEGORIE_ID_SEQ,
            Sequences.CLASS_COMPTE_ID_SEQ,
            Sequences.CONNEXION_ID_SEQ,
            Sequences.DEPENSE_ID_SEQ,
            Sequences.DIRECTION_ID_SEQ,
            Sequences.DIVISION_ID_SEQ,
            Sequences.ECRITURE_ID_SEQ,
            Sequences.EMAIL_ID_SEQ,
            Sequences.JOURNAL_ECRITURE_ID_SEQ,
            Sequences.PARAMS_ID_SEQ,
            Sequences.PROGRAMME_ID_SEQ,
            Sequences.REGION_ID_SEQ,
            Sequences.REGLEMENT_DETAIL_ID_SEQ,
            Sequences.REGLEMENT_ID_SEQ,
            Sequences.SERVICE_ID_SEQ,
            Sequences.STRUCTURE_PARTENAIRE_ID_SEQ,
            Sequences.TYPE_PRESTATION_ID_SEQ,
            Sequences.ZIMBRA_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Adherent.ADHERENT,
            AdherentTmp.ADHERENT_TMP,
            AyantDroit.AYANT_DROIT,
            Budget.BUDGET,
            Categorie.CATEGORIE,
            CategorieCompte.CATEGORIE_COMPTE,
            ClassCompte.CLASS_COMPTE,
            Connexion.CONNEXION,
            Depense.DEPENSE,
            Direction.DIRECTION,
            Division.DIVISION,
            Ecriture.ECRITURE,
            Email.EMAIL,
            JournalEcriture.JOURNAL_ECRITURE,
            Params.PARAMS,
            Personnel.PERSONNEL,
            Programme.PROGRAMME,
            Region.REGION,
            Reglement.REGLEMENT,
            ReglementDetail.REGLEMENT_DETAIL,
            Service.SERVICE,
            StructurePartenaire.STRUCTURE_PARTENAIRE,
            TypePrestation.TYPE_PRESTATION,
            Users.USERS,
            VAdherent.V_ADHERENT,
            VAdherentAyantDroit.V_ADHERENT_AYANT_DROIT,
            VAyantDroit.V_AYANT_DROIT,
            VBudget.V_BUDGET,
            VCumuleByStructure.V_CUMULE_BY_STRUCTURE,
            VCumuleByStructureTypePrestation.V_CUMULE_BY_STRUCTURE_TYPE_PRESTATION,
            VCumuleByTypePrestation.V_CUMULE_BY_TYPE_PRESTATION,
            VDepassement.V_DEPASSEMENT,
            VEcriture.V_ECRITURE,
            VEffectifMains.V_EFFECTIF_MAINS,
            VEffectifMainsAyantDroit.V_EFFECTIF_MAINS_AYANT_DROIT,
            VNbrBenefiaireParPrestation.V_NBR_BENEFIAIRE_PAR_PRESTATION,
            VNbrPrestationParAdherent.V_NBR_PRESTATION_PAR_ADHERENT,
            VPartenaire.V_PARTENAIRE,
            VReglement.V_REGLEMENT,
            VReglement_2.V_REGLEMENT_2,
            VReglementGlobal.V_REGLEMENT_GLOBAL,
            VReglementGlobalByAdherent.V_REGLEMENT_GLOBAL_BY_ADHERENT,
            VReglementGlobalParType.V_REGLEMENT_GLOBAL_PAR_TYPE,
            VReglementGlobale.V_REGLEMENT_GLOBALE,
            VSituationStructureAdherent.V_SITUATION_STRUCTURE_ADHERENT,
            VSituationStructurePrestationAdherent.V_SITUATION_STRUCTURE_PRESTATION_ADHERENT,
            VTotalAdherents.V_TOTAL_ADHERENTS,
            VTotalAyantDroitConjoint.V_TOTAL_AYANT_DROIT_CONJOINT,
            VTotalAyantDroitEnfant.V_TOTAL_AYANT_DROIT_ENFANT,
            Zimbra.ZIMBRA);
    }
}
