/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.adherent_id_seq</code>
     */
    public static final Sequence<Long> ADHERENT_ID_SEQ = new SequenceImpl<Long>("adherent_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.adherent_tmp_id_seq</code>
     */
    public static final Sequence<Long> ADHERENT_TMP_ID_SEQ = new SequenceImpl<Long>("adherent_tmp_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.ayant_droit_id_seq</code>
     */
    public static final Sequence<Long> AYANT_DROIT_ID_SEQ = new SequenceImpl<Long>("ayant_droit_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.budget_id_seq</code>
     */
    public static final Sequence<Long> BUDGET_ID_SEQ = new SequenceImpl<Long>("budget_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categorie_compte_id_seq</code>
     */
    public static final Sequence<Long> CATEGORIE_COMPTE_ID_SEQ = new SequenceImpl<Long>("categorie_compte_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categorie_id_seq</code>
     */
    public static final Sequence<Long> CATEGORIE_ID_SEQ = new SequenceImpl<Long>("categorie_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.class_compte_id_seq</code>
     */
    public static final Sequence<Long> CLASS_COMPTE_ID_SEQ = new SequenceImpl<Long>("class_compte_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.connexion_id_seq</code>
     */
    public static final Sequence<Long> CONNEXION_ID_SEQ = new SequenceImpl<Long>("connexion_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.depense_id_seq</code>
     */
    public static final Sequence<Long> DEPENSE_ID_SEQ = new SequenceImpl<Long>("depense_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.direction_id_seq</code>
     */
    public static final Sequence<Long> DIRECTION_ID_SEQ = new SequenceImpl<Long>("direction_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.division_id_seq</code>
     */
    public static final Sequence<Long> DIVISION_ID_SEQ = new SequenceImpl<Long>("division_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.ecriture_id_seq</code>
     */
    public static final Sequence<Long> ECRITURE_ID_SEQ = new SequenceImpl<Long>("ecriture_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.email_id_seq</code>
     */
    public static final Sequence<Long> EMAIL_ID_SEQ = new SequenceImpl<Long>("email_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.journal_ecriture_id_seq</code>
     */
    public static final Sequence<Long> JOURNAL_ECRITURE_ID_SEQ = new SequenceImpl<Long>("journal_ecriture_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.params_id_seq</code>
     */
    public static final Sequence<Long> PARAMS_ID_SEQ = new SequenceImpl<Long>("params_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.programme_id_seq</code>
     */
    public static final Sequence<Long> PROGRAMME_ID_SEQ = new SequenceImpl<Long>("programme_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.region_id_seq</code>
     */
    public static final Sequence<Long> REGION_ID_SEQ = new SequenceImpl<Long>("region_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.reglement_detail_id_seq</code>
     */
    public static final Sequence<Long> REGLEMENT_DETAIL_ID_SEQ = new SequenceImpl<Long>("reglement_detail_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.reglement_id_seq</code>
     */
    public static final Sequence<Long> REGLEMENT_ID_SEQ = new SequenceImpl<Long>("reglement_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.service_id_seq</code>
     */
    public static final Sequence<Long> SERVICE_ID_SEQ = new SequenceImpl<Long>("service_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.structure_partenaire_id_seq</code>
     */
    public static final Sequence<Long> STRUCTURE_PARTENAIRE_ID_SEQ = new SequenceImpl<Long>("structure_partenaire_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.type_prestation_id_seq</code>
     */
    public static final Sequence<Long> TYPE_PRESTATION_ID_SEQ = new SequenceImpl<Long>("type_prestation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.zimbra_id_seq</code>
     */
    public static final Sequence<Long> ZIMBRA_ID_SEQ = new SequenceImpl<Long>("zimbra_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
